(()=>{
'use strict';
const SUPABASE_URL='https://rgbweaimkcndjznlazho.supabase.co';
const SUPABASE_KEY='sb_publishable_S3IEOR8vkWkXEdGtx8fGjw_nH8c4fV3';
const ADMIN_ENDPOINT=SUPABASE_URL+'/functions/v1/academy-admin';
const ACADEMY_URL='/atelier-v2/academy-v2.html';
const COURSE_FIX='/atelier-v2/academy/course-current.js?v=20260903-drive-titles';
const sb=window.supabase.createClient(SUPABASE_URL,SUPABASE_KEY,{auth:{persistSession:true,autoRefreshToken:true,detectSessionInUrl:true}});
const $=id=>document.getElementById(id);
const META={
 design:{title:'Design & Flyers',short:'Skill 1',desc:'The current Design & Flyers course from your source library.'},
 video:{title:'AI UGC & Influencer',short:'Skill 2',desc:'The current AI UGC & Influencer course from your source library.'},
 landing:{title:'Landing Page Design',short:'Skill 3',desc:'The current Landing Page Design course from your source library.'},
 money:{title:'The Money Engine System',short:'Money Engine',desc:'The current Money Engine client-acquisition system.'}
};
const state={session:null,rows:[],rowMap:new Map(),courses:[],course:null,lesson:null,filter:'all',search:'',returnView:'course'};
let toastTimer;

function esc(v){return String(v??'').replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]))}
function toast(msg,bad=false){const e=$('toast');if(!e)return;e.textContent=msg;e.className='toast show'+(bad?' bad':'');clearTimeout(toastTimer);toastTimer=setTimeout(()=>e.className='toast',3500)}
function connected(r){return !!(r&&r.has_video&&r.url&&String(r.url).trim())}
function rowFor(k){return state.rowMap.get(k)||null}
function fmtDate(v){if(!v)return'Never';const d=new Date(v);return Number.isNaN(d.getTime())?'Unknown':d.toLocaleString([], {year:'numeric',month:'short',day:'numeric',hour:'2-digit',minute:'2-digit'})}
function fmtDuration(sec){if(sec===null||sec===undefined||sec==='')return'—';let n=Math.max(0,Math.round(Number(sec)||0));const h=Math.floor(n/3600),m=Math.floor((n%3600)/60),s=n%60;return h?`${h}:${String(m).padStart(2,'0')}:${String(s).padStart(2,'0')}`:`${m}:${String(s).padStart(2,'0')}`}
function parseDuration(raw){const v=String(raw??'').trim();if(!v)return{ok:true,value:null};if(/^\d+$/.test(v)){const n=Number(v);return n<=86400?{ok:true,value:n}:{ok:false,error:'Duration is too long.'}}const p=v.split(':');if(p.length<2||p.length>3||p.some(x=>!/^\d+$/.test(x)))return{ok:false,error:'Use MM:SS, HH:MM:SS, or seconds.'};const a=p.map(Number);const sec=p.length===2?a[0]*60+a[1]:a[0]*3600+a[1]*60+a[2];if((p.length===2&&a[1]>59)||(p.length===3&&(a[1]>59||a[2]>59))||sec>86400)return{ok:false,error:'Check the duration format.'};return{ok:true,value:sec}}
function youtube(raw){const value=String(raw??'').trim();if(!value)return{ok:false,error:'Paste a YouTube URL.'};let u;try{u=new URL(value)}catch{return{ok:false,error:'Enter a valid URL.'}}if(u.protocol!=='https:')return{ok:false,error:'Use an HTTPS YouTube URL.'};const host=u.hostname.replace(/^www\./i,'').toLowerCase(),parts=u.pathname.split('/').filter(Boolean);let id='';if(host==='youtu.be')id=parts[0]||'';else if(['youtube.com','m.youtube.com','youtube-nocookie.com'].includes(host)){if(u.pathname==='/watch')id=u.searchParams.get('v')||'';else if(['shorts','embed','live'].includes(parts[0]||''))id=parts[1]||''}else return{ok:false,error:'Use youtube.com or youtu.be.'};if(!/^[A-Za-z0-9_-]{6,20}$/.test(id))return{ok:false,error:'Could not read the YouTube video ID.'};return{ok:true,id,canonical:`https://www.youtube.com/watch?v=${id}`,embed:`https://www.youtube-nocookie.com/embed/${encodeURIComponent(id)}?rel=0&playsinline=1`}}

function loadCurriculum(){return new Promise((resolve,reject)=>{if(window.__FUSE_CURRENT_CURRICULUM__)return resolve();const s=document.createElement('script');s.src=COURSE_FIX;s.onload=resolve;s.onerror=()=>reject(new Error('Could not load the current Academy curriculum.'));document.head.appendChild(s)})}
function flatten(id,c){const meta=META[id],lessons=[];(c.modules||[]).forEach((m,mi)=>(m.lessons||[]).forEach((l,li)=>lessons.push({courseId:id,courseTitle:meta.title,key:l.key,title:l.title||`Lesson ${li+1}`,n:l.n||'',dur:l.dur||'',moduleTitle:m.title||`Module ${mi+1}`,moduleKey:m.key||'',moduleIndex:mi,lessonIndex:li})));return{id,title:meta.title,short:meta.short,desc:meta.desc,source:c,lessons}}
function buildCourses(){const ps=(window.FUSE_COURSE&&Array.isArray(window.FUSE_COURSE.pillars))?window.FUSE_COURSE.pillars:[],get=k=>ps.find(p=>p.key===k);const missing=['design','video','landing'].filter(k=>!get(k));if(missing.length)throw new Error('Academy course data is missing: '+missing.join(', '));const money=window.FUSE_ACADEMY_MONEY;if(!money)throw new Error('Money Engine course data is missing.');state.courses=[flatten('design',get('design')),flatten('video',get('video')),flatten('landing',get('landing')),flatten('money',money)]}
function allLessons(){return state.courses.flatMap(c=>c.lessons)}
function stats(c){const total=c.lessons.length,done=c.lessons.filter(l=>connected(rowFor(l.key))).length;return{total,done,missing:total-done,pct:total?Math.round(done/total*100):0}}
async function session(){const{data,error}=await sb.auth.getSession();if(error)throw error;return data.session||null}
async function api(method='GET',body=null){const s=await session();if(!s)throw Object.assign(new Error('Please sign in again.'),{status:401});state.session=s;const r=await fetch(ADMIN_ENDPOINT,{method,headers:{Authorization:'Bearer '+s.access_token,apikey:SUPABASE_KEY,'Content-Type':'application/json'},body:body?JSON.stringify(body):undefined,cache:'no-store'});let d={};try{d=await r.json()}catch{}if(!r.ok)throw Object.assign(new Error(d.error||`Admin request failed (${r.status}).`),{status:r.status});return d}
async function loadLibrary(){const d=await api();state.rows=Array.isArray(d.rows)?d.rows:[];state.rowMap=new Map(state.rows.map(r=>[r.lesson_key,r]));$('accountEmail').textContent=d.user?.email||state.session?.user?.email||'Admin';renderDashboard();if(state.course)renderCourse();return d}

function authView(mode='login',message=''){$('authGate').classList.remove('hidden');$('app').classList.add('hidden');$('authLoading').classList.add('hidden');$('loginForm').classList.toggle('hidden',mode!=='login');$('deniedView').classList.toggle('hidden',mode!=='denied');if(message&&mode==='login'){const m=$('loginMessage');m.textContent=message;m.classList.remove('hidden')}}
function loadingAuth(){$('authGate').classList.remove('hidden');$('app').classList.add('hidden');$('authLoading').classList.remove('hidden');$('loginForm').classList.add('hidden');$('deniedView').classList.add('hidden')}
function showApp(){$('authGate').classList.add('hidden');$('app').classList.remove('hidden');showView('dashboard')}
function showView(name){['dashboard','course','editor','bulk'].forEach(v=>$(v+'View').classList.toggle('hidden',v!==name));window.scrollTo({top:0,behavior:'smooth'})}
async function boot(){loadingAuth();try{await loadCurriculum();buildCourses();const s=await session();if(!s)return authView('login');state.session=s;try{await loadLibrary();showApp()}catch(e){if(e.status===403)authView('denied');else if(e.status===401){await sb.auth.signOut();authView('login','Your session expired. Sign in again.')}else authView('login',e.message)}}catch(e){authView('login','Could not start Academy Admin: '+e.message)}}
async function signIn(){const email=$('loginEmail').value.trim(),password=$('loginPassword').value;if(!email||!password)return authView('login','Enter your email and password.');$('loginBtn').disabled=true;$('loginBtn').textContent='Signing in…';$('loginMessage').classList.add('hidden');try{const{data,error}=await sb.auth.signInWithPassword({email,password});if(error)throw error;state.session=data.session;try{await loadLibrary();showApp()}catch(e){if(e.status===403)authView('denied');else throw e}}catch(e){authView('login',e.message||'Could not sign in.')}finally{$('loginBtn').disabled=false;$('loginBtn').textContent='Sign in to Academy Admin'}}
async function signOut(){await sb.auth.signOut();state.session=null;state.rows=[];state.rowMap.clear();authView('login')}

function renderDashboard(){const lessons=allLessons(),done=lessons.filter(l=>connected(rowFor(l.key))).length;$('summaryStats').innerHTML=`<div class="stat"><b>${state.courses.length}</b><span>Total courses</span></div><div class="stat"><b>${lessons.length}</b><span>Total lessons</span></div><div class="stat"><b>${done}</b><span>Videos connected</span></div><div class="stat"><b>${lessons.length-done}</b><span>Missing videos</span></div>`;$('courseGrid').innerHTML=state.courses.map((c,i)=>{const s=stats(c);return`<article class="course-card"><div class="course-card-top"><div class="course-index">0${i+1}</div><span class="status-pill ${s.missing?'missing':'connected'}"><span class="status-dot"></span>${s.missing?s.missing+' missing':'Complete'}</span></div><h3>${esc(c.title)}</h3><p>${esc(c.desc)}</p><div class="course-metrics"><span>${s.done} / ${s.total} videos connected</span><span>${s.pct}%</span></div><div class="progress"><i style="width:${s.pct}%"></i></div><button class="primary manage-course" type="button" data-course="${c.id}">Manage course →</button></article>`}).join('');const current=new Set(lessons.map(l=>l.key)),legacy=state.rows.filter(r=>connected(r)&&!current.has(r.lesson_key)),note=$('legacyNote');if(legacy.length){note.classList.remove('hidden');note.innerHTML=`<b>${legacy.length} legacy/unmapped video record${legacy.length===1?'':'s'} preserved.</b> They are left untouched rather than being guessed into the current curriculum.`}else note.classList.add('hidden');document.querySelectorAll('.manage-course').forEach(b=>b.onclick=()=>openCourse(b.dataset.course))}
function openCourse(id){state.course=state.courses.find(c=>c.id===id);if(!state.course)return;state.filter='all';state.search='';$('lessonSearch').value='';document.querySelectorAll('.filter').forEach(b=>b.classList.toggle('active',b.dataset.filter==='all'));renderCourse();showView('course')}
function renderCourse(){const c=state.course;if(!c)return;const s=stats(c);$('courseTitle').textContent=c.title;$('courseSubtitle').textContent=`${s.total} lessons · ${s.done} connected · ${s.missing} missing`;$('courseSummary').innerHTML=`<div class="summary-copy"><b>${esc(c.short)} · ${esc(c.title)}</b><p>Synced to the current source curriculum.</p><div class="progress"><i style="width:${s.pct}%"></i></div></div><div class="summary-numbers"><span>${s.done} connected</span><span>${s.missing} missing</span><span>${s.pct}% complete</span></div>`;const q=state.search.toLowerCase().trim(),visible=c.lessons.filter(l=>{const ok=connected(rowFor(l.key));if(state.filter==='connected'&&!ok)return false;if(state.filter==='missing'&&ok)return false;return !q||l.title.toLowerCase().includes(q)||l.key.toLowerCase().includes(q)||l.moduleTitle.toLowerCase().includes(q)}),list=$('lessonList');if(!visible.length){list.innerHTML='<div class="empty">No lessons match this filter.</div>';return}list.innerHTML=visible.map(l=>{const r=rowFor(l.key),ok=connected(r);return`<article class="lesson-row"><div><div class="lesson-kicker">${esc(l.moduleTitle)}</div><div class="lesson-title">${esc(l.title)}</div><div class="lesson-key">${esc(l.key)}</div><div class="lesson-meta-line"><span>Duration: ${ok&&r.duration_sec!=null?fmtDuration(r.duration_sec):(l.dur||'—')}</span><span>Updated: ${ok?fmtDate(r.updated_at):'Never'}</span></div></div><div class="lesson-right"><span class="status-pill ${ok?'connected':'missing'}"><span class="status-dot"></span>${ok?'Video connected':'Missing video'}</span><div class="row-actions"><button class="mini-btn primary-mini" data-edit="${esc(l.key)}" type="button">${ok?'Edit':'Add video'}</button>${ok?`<button class="mini-btn" data-preview="${esc(l.key)}" type="button">Preview</button><button class="mini-btn danger-mini" data-remove="${esc(l.key)}" type="button">Remove</button>`:''}<button class="mini-btn" data-open-academy type="button">Open Academy</button></div></div></article>`}).join('');list.querySelectorAll('[data-edit]').forEach(b=>b.onclick=()=>openEditor(b.dataset.edit));list.querySelectorAll('[data-preview]').forEach(b=>b.onclick=()=>preview(b.dataset.preview));list.querySelectorAll('[data-remove]').forEach(b=>b.onclick=()=>removeVideo(b.dataset.remove));list.querySelectorAll('[data-open-academy]').forEach(b=>b.onclick=()=>window.open(ACADEMY_URL,'_blank','noopener'))}
function findLesson(key){for(const c of state.courses){const l=c.lessons.find(x=>x.key===key);if(l)return{course:c,lesson:l}}return null}
function openEditor(key){const f=findLesson(key);if(!f)return;state.course=f.course;state.lesson=f.lesson;const l=f.lesson,r=rowFor(key);$('editorHeading').textContent=connected(r)?'Edit lesson video':'Add lesson video';$('editorCourse').textContent=f.course.title;$('editorModule').textContent=l.moduleTitle;$('editorLesson').textContent=l.title;$('editorKey').textContent=l.key;$('videoUrl').value=r?.url||'';$('videoDuration').value=r?.duration_sec!=null?fmtDuration(r.duration_sec):'';renderEditorStatus();renderEditorPreview();showView('editor')}
function renderEditorStatus(){const r=rowFor(state.lesson?.key),ok=connected(r);$('currentStatus').innerHTML=ok?`<b>Connected.</b> Last updated ${esc(fmtDate(r.updated_at))}.`:'<b>Missing video.</b> Paste an unlisted YouTube link and save it.';$('removeVideoBtn').disabled=!ok}
function renderEditorPreview(){const box=$('editorPreview'),y=youtube($('videoUrl').value);box.innerHTML='';if(!y.ok){box.innerHTML='<div class="preview-copy"><b>Paste a valid YouTube link</b>Your vertical lesson preview appears here.</div>';return}box.innerHTML=`<iframe src="${y.embed}" title="Lesson video preview" allow="accelerometer; autoplay; encrypted-media; picture-in-picture; fullscreen" allowfullscreen></iframe>`}
async function saveEditor(){const l=state.lesson;if(!l)return;const y=youtube($('videoUrl').value),dur=parseDuration($('videoDuration').value);if(!y.ok)return toast(y.error,true);if(!dur.ok)return toast(dur.error,true);const b=$('saveVideoBtn');b.disabled=true;b.textContent='Saving…';try{const d=await api('POST',{action:'upsert',lesson_key:l.key,url:y.canonical,duration_sec:dur.value});if(d.row){state.rowMap.set(d.row.lesson_key,d.row);state.rows=[...state.rowMap.values()]}$('videoUrl').value=d.row?.url||y.canonical;$('videoDuration').value=d.row?.duration_sec!=null?fmtDuration(d.row.duration_sec):'';renderEditorStatus();renderEditorPreview();renderDashboard();toast('Lesson video saved.')}catch(e){toast(e.message,true)}finally{b.disabled=false;b.textContent='Save Lesson Video'}}
async function removeVideo(key=state.lesson?.key){if(!key)return;const f=findLesson(key),title=f?.lesson?.title||key;if(!confirm(`Remove the video from “${title}”? The lesson itself will stay in Academy.`))return;try{const d=await api('POST',{action:'clear',lesson_key:key});if(d.row){state.rowMap.set(d.row.lesson_key,d.row);state.rows=[...state.rowMap.values()]}renderDashboard();if(state.course)renderCourse();if(state.lesson?.key===key){$('videoUrl').value='';$('videoDuration').value='';renderEditorStatus();renderEditorPreview()}toast('Video removed.')}catch(e){toast(e.message,true)}}
function preview(key){const f=findLesson(key),r=rowFor(key),y=youtube(r?.url);if(!f||!connected(r)||!y.ok)return toast('This saved URL is not a supported YouTube link.',true);$('dialogTitle').textContent=f.lesson.title;$('dialogPlayer').innerHTML=`<iframe src="${y.embed}" title="${esc(f.lesson.title)}" allow="accelerometer; autoplay; encrypted-media; picture-in-picture; fullscreen" allowfullscreen></iframe>`;$('previewDialog').showModal()}
function openBulk(id=state.course?.id||state.courses[0]?.id){$('bulkCourse').innerHTML=state.courses.map(c=>`<option value="${c.id}">${esc(c.title)}</option>`).join('');if(id)$('bulkCourse').value=id;renderBulk();showView('bulk')}
function renderBulk(){const c=state.courses.find(x=>x.id===$('bulkCourse').value)||state.courses[0];state.course=c;$('bulkList').innerHTML=c.lessons.map(l=>{const r=rowFor(l.key),url=r?.url||'',dur=r?.duration_sec!=null?fmtDuration(r.duration_sec):'';return`<div class="bulk-row" data-bulk-key="${esc(l.key)}" data-initial-url="${esc(url)}" data-initial-duration="${esc(String(r?.duration_sec??''))}"><div class="bulk-name"><b>${esc(l.title)}</b><span>${esc(l.key)}</span></div><input class="bulk-url" type="url" inputmode="url" value="${esc(url)}" placeholder="Paste YouTube URL"><input class="bulk-duration" inputmode="numeric" value="${esc(dur)}" placeholder="09:32"></div>`}).join('');$('bulkStatus').textContent=`${c.lessons.length} lessons · existing URLs are prefilled · blank missing lessons are ignored.`}
async function saveBulk(){const items=[];for(const row of $('bulkList').querySelectorAll('.bulk-row')){row.classList.remove('invalid');const key=row.dataset.bulkKey,raw=row.querySelector('.bulk-url').value.trim();if(!raw)continue;const y=youtube(raw),dur=parseDuration(row.querySelector('.bulk-duration').value);if(!y.ok||!dur.ok){row.classList.add('invalid');return toast(`${key}: ${y.ok?dur.error:y.error}`,true)}const old=row.dataset.initialUrl?youtube(row.dataset.initialUrl):null,nextDur=dur.value===null?'':String(dur.value);if(old?.ok&&old.id===y.id&&nextDur===(row.dataset.initialDuration||''))continue;items.push({lesson_key:key,url:y.canonical,duration_sec:dur.value})}if(!items.length)return toast('No new or changed video links to save.');const b=$('bulkSaveBtn');b.disabled=true;b.textContent=`Saving ${items.length}…`;try{const d=await api('POST',{action:'bulk_upsert',items});(d.rows||[]).forEach(r=>state.rowMap.set(r.lesson_key,r));state.rows=[...state.rowMap.values()];renderDashboard();renderBulk();toast(`${d.count||items.length} video${items.length===1?'':'s'} saved.`)}catch(e){toast(e.message,true)}finally{b.disabled=false;b.textContent='Save all videos'}}
function bind(){$('loginBtn').onclick=signIn;$('loginPassword').addEventListener('keydown',e=>{if(e.key==='Enter')signIn()});$('deniedSignOut').onclick=signOut;$('signOutBtn').onclick=signOut;$('refreshBtn').onclick=async()=>{try{await loadLibrary();toast('Video library refreshed.')}catch(e){toast(e.message,true)}};$('dashboardBulkBtn').onclick=()=>openBulk();$('courseBack').onclick=()=>{renderDashboard();showView('dashboard')};$('courseBulkBtn').onclick=()=>openBulk(state.course?.id);$('lessonSearch').oninput=e=>{state.search=e.target.value;renderCourse()};document.querySelectorAll('.filter').forEach(b=>b.onclick=()=>{state.filter=b.dataset.filter;document.querySelectorAll('.filter').forEach(x=>x.classList.toggle('active',x===b));renderCourse()});$('editorBack').onclick=()=>{renderCourse();showView('course')};$('videoUrl').oninput=renderEditorPreview;$('saveVideoBtn').onclick=saveEditor;$('removeVideoBtn').onclick=()=>removeVideo();$('openAcademyBtn').onclick=()=>window.open(ACADEMY_URL,'_blank','noopener');$('bulkBack').onclick=()=>{if(state.course){renderCourse();showView('course')}else showView('dashboard')};$('bulkCourse').onchange=renderBulk;$('bulkRefresh').onclick=renderBulk;$('bulkSaveBtn').onclick=saveBulk;$('dialogClose').onclick=()=>$('previewDialog').close();$('previewDialog').addEventListener('close',()=>{$('dialogPlayer').innerHTML=''});sb.auth.onAuthStateChange((event,s)=>{state.session=s;if(event==='SIGNED_OUT')authView('login')})}
bind();boot();
})();
