(()=>{
'use strict';

const SUPABASE_URL='https://rgbweaimkcndjznlazho.supabase.co';
const SUPABASE_KEY='sb_publishable_S3IEOR8vkWkXEdGtx8fGjw_nH8c4fV3';
const ADMIN_ENDPOINT=SUPABASE_URL+'/functions/v1/academy-admin';
const ACADEMY_URL='/atelier-v2/academy-v2.html';
const sb=window.supabase.createClient(SUPABASE_URL,SUPABASE_KEY,{auth:{persistSession:true,autoRefreshToken:true,detectSessionInUrl:true}});
const $=id=>document.getElementById(id);

const MONEY={
  key:'money',name:'The Money Engine System',sub:'Turn your skill into clients',modules:[
    {key:'money-start',title:'Start Here',lessons:[{key:'money-start',n:'0',title:'Start Here — Understand The System',dur:''}]},
    {key:'money-main',title:'The Money Engine System',lessons:[
      {key:'money-m1',n:'1',title:'How It Works',dur:''},
      {key:'money-m2',n:'2',title:'The 50 — Lead Hunt',dur:''},
      {key:'money-m3',n:'3',title:'Find The Problem',dur:''},
      {key:'money-m4',n:'4',title:'The Sample Engine',dur:''},
      {key:'money-m5',n:'5',title:'Pitch & Follow Up',dur:''},
      {key:'money-m6',n:'6',title:'Close The Deal',dur:''}
    ]}
  ]
};

const COURSE_META={
  design:{title:'Design & Flyers',short:'Skill 1',desc:'The current learner-facing design and flyer curriculum.',source:'design'},
  video:{title:'AI UGC & Influencer',short:'Skill 2',desc:'The current AI video and UGC curriculum used by Academy.',source:'video'},
  landing:{title:'Landing Page Design',short:'Skill 3',desc:'The current landing-page curriculum used by Academy.',source:'landing'},
  money:{title:'The Money Engine System',short:'Money Engine',desc:'The current seven-step Money Engine path used by Academy.',source:'money'}
};

const state={session:null,rows:[],rowMap:new Map(),courses:[],course:null,lesson:null,filter:'all',search:'',returnView:'course'};
let toastTimer=null;

function toast(message,bad=false){const el=$('toast');el.textContent=message;el.className='toast show'+(bad?' bad':'');clearTimeout(toastTimer);toastTimer=setTimeout(()=>{el.className='toast'},3600)}
function escapeHtml(value){return String(value??'').replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]))}
function connected(row){return !!(row&&row.has_video&&row.url&&String(row.url).trim())}
function rowFor(key){return state.rowMap.get(key)||null}
function fmtDate(value){if(!value)return'Never';const d=new Date(value);if(Number.isNaN(d.getTime()))return'Unknown';return d.toLocaleString([], {year:'numeric',month:'short',day:'numeric',hour:'2-digit',minute:'2-digit'})}
function fmtDuration(sec){if(sec===null||sec===undefined||sec==='')return'—';const n=Math.max(0,Math.round(Number(sec)||0)),h=Math.floor(n/3600),m=Math.floor((n%3600)/60),s=n%60;return h?`${h}:${String(m).padStart(2,'0')}:${String(s).padStart(2,'0')}`:`${m}:${String(s).padStart(2,'0')}`}
function parseDuration(raw){const v=String(raw??'').trim();if(!v)return{ok:true,value:null};if(/^\d+$/.test(v)){const n=Number(v);return n<=86400?{ok:true,value:n}:{ok:false,error:'Duration is too long.'}}const p=v.split(':');if(p.length<2||p.length>3||p.some(x=>!/^\d+$/.test(x)))return{ok:false,error:'Use MM:SS, HH:MM:SS, or seconds.'};const nums=p.map(Number);let sec=p.length===2?nums[0]*60+nums[1]:nums[0]*3600+nums[1]*60+nums[2];if((p.length===2&&nums[1]>59)||(p.length===3&&(nums[1]>59||nums[2]>59))||sec>86400)return{ok:false,error:'Check the duration format.'};return{ok:true,value:sec}}

function youtubeInfo(raw){const value=String(raw??'').trim();if(!value)return{ok:false,error:'Paste a YouTube URL.'};let u;try{u=new URL(value)}catch{return{ok:false,error:'Enter a valid URL.'}}if(u.protocol!=='https:')return{ok:false,error:'Use an HTTPS YouTube URL.'};const host=u.hostname.replace(/^www\./i,'').toLowerCase();const parts=u.pathname.split('/').filter(Boolean);let id='';if(host==='youtu.be')id=parts[0]||'';else if(['youtube.com','m.youtube.com','youtube-nocookie.com'].includes(host)){if(u.pathname==='/watch')id=u.searchParams.get('v')||'';else if(['shorts','embed','live'].includes(parts[0]||''))id=parts[1]||''}else return{ok:false,error:'Use youtube.com or youtu.be.'};if(!/^[A-Za-z0-9_-]{6,20}$/.test(id))return{ok:false,error:'Could not read the YouTube video ID.'};return{ok:true,id,canonical:`https://www.youtube.com/watch?v=${id}`,embed:`https://www.youtube-nocookie.com/embed/${encodeURIComponent(id)}?rel=0&playsinline=1`}}

function flattenCourse(id,course){const meta=COURSE_META[id];const lessons=[];(course.modules||[]).forEach((mod,mi)=>(mod.lessons||[]).forEach((lesson,li)=>lessons.push({
  courseId:id,courseTitle:meta.title,key:lesson.key,title:lesson.title||`Lesson ${li+1}`,n:lesson.n||'',dur:lesson.dur||'',moduleTitle:mod.title||`Module ${mi+1}`,moduleKey:mod.key||'',moduleIndex:mi,lessonIndex:li
})));return{id,title:meta.title,short:meta.short,desc:meta.desc,source:course,lessons}}

function buildCourses(){const pillars=(window.FUSE_COURSE&&Array.isArray(window.FUSE_COURSE.pillars))?window.FUSE_COURSE.pillars:[];const get=k=>pillars.find(p=>p.key===k);const required=['design','video','landing'];const missing=required.filter(k=>!get(k));if(missing.length)throw new Error('Academy course data is missing: '+missing.join(', '));state.courses=[flattenCourse('design',get('design')),flattenCourse('video',get('video')),flattenCourse('landing',get('landing')),flattenCourse('money',MONEY)];}
function allLessons(){return state.courses.flatMap(c=>c.lessons)}
function statsFor(course){const total=course.lessons.length,done=course.lessons.filter(l=>connected(rowFor(l.key))).length;return{total,done,missing:total-done,pct:total?Math.round(done/total*100):0}}

async function getSession(){const{data,error}=await sb.auth.getSession();if(error)throw error;return data.session||null}
async function adminApi(method='GET',body=null){const session=await getSession();if(!session)throw Object.assign(new Error('Please sign in again.'),{status:401});state.session=session;const res=await fetch(ADMIN_ENDPOINT,{method,headers:{'Authorization':'Bearer '+session.access_token,'apikey':SUPABASE_KEY,'Content-Type':'application/json'},body:body?JSON.stringify(body):undefined,cache:'no-store'});let data={};try{data=await res.json()}catch{}if(!res.ok)throw Object.assign(new Error(data.error||`Admin request failed (${res.status}).`),{status:res.status,data});return data}
async function loadLibrary(){const data=await adminApi('GET');state.rows=Array.isArray(data.rows)?data.rows:[];state.rowMap=new Map(state.rows.map(r=>[r.lesson_key,r]));$('accountEmail').textContent=data.user?.email||state.session?.user?.email||'Admin';renderDashboard();if(state.course)renderCourse();return data}

function showAuth(mode='login',message=''){$('authGate').classList.remove('hidden');$('app').classList.add('hidden');$('authLoading').classList.add('hidden');$('loginForm').classList.toggle('hidden',mode!=='login');$('deniedView').classList.toggle('hidden',mode!=='denied');if(message&&mode==='login'){const m=$('loginMessage');m.textContent=message;m.classList.remove('hidden')}}
function showLoadingAuth(){$('authGate').classList.remove('hidden');$('app').classList.add('hidden');$('authLoading').classList.remove('hidden');$('loginForm').classList.add('hidden');$('deniedView').classList.add('hidden')}
function showApp(){$('authGate').classList.add('hidden');$('app').classList.remove('hidden');showView('dashboard')}
function showView(name){['dashboard','course','editor','bulk'].forEach(v=>$(v+'View').classList.toggle('hidden',v!==name));window.scrollTo({top:0,behavior:'smooth'})}

async function bootstrapSession(){showLoadingAuth();try{buildCourses();const session=await getSession();if(!session){showAuth('login');return}state.session=session;try{await loadLibrary();showApp()}catch(e){if(e.status===403)showAuth('denied');else if(e.status===401){await sb.auth.signOut();showAuth('login','Your session expired. Sign in again.')}else showAuth('login',e.message)}}catch(e){showAuth('login','Could not start Academy Admin: '+e.message)}}

async function signIn(){const email=$('loginEmail').value.trim(),password=$('loginPassword').value;if(!email||!password){showAuth('login','Enter your email and password.');return}$('loginBtn').disabled=true;$('loginBtn').textContent='Signing in…';$('loginMessage').classList.add('hidden');try{const{data,error}=await sb.auth.signInWithPassword({email,password});if(error)throw error;state.session=data.session;try{await loadLibrary();showApp()}catch(e){if(e.status===403)showAuth('denied');else throw e}}catch(e){showAuth('login',e.message||'Could not sign in.')}finally{$('loginBtn').disabled=false;$('loginBtn').textContent='Sign in to Academy Admin'}}
async function signOut(){await sb.auth.signOut();state.session=null;state.rows=[];state.rowMap.clear();showAuth('login')}

function renderDashboard(){const totals=allLessons(),connectedCount=totals.filter(l=>connected(rowFor(l.key))).length,missing=totals.length-connectedCount;$('summaryStats').innerHTML=`
  <div class="stat"><b>${state.courses.length}</b><span>Total courses</span></div>
  <div class="stat"><b>${totals.length}</b><span>Total lessons</span></div>
  <div class="stat"><b>${connectedCount}</b><span>Videos connected</span></div>
  <div class="stat"><b>${missing}</b><span>Missing videos</span></div>`;
  $('courseGrid').innerHTML=state.courses.map((c,i)=>{const s=statsFor(c);return`<article class="course-card" data-course="${c.id}"><div class="course-card-top"><div class="course-index">0${i+1}</div><span class="status-pill ${s.missing?'missing':'connected'}"><span class="status-dot"></span>${s.missing?s.missing+' missing':'Complete'}</span></div><h3>${escapeHtml(c.title)}</h3><p>${escapeHtml(c.desc)}</p><div class="course-metrics"><span>${s.done} / ${s.total} videos connected</span><span>${s.pct}%</span></div><div class="progress"><i style="width:${s.pct}%"></i></div><button class="primary manage-course" type="button" data-course="${c.id}">Manage course →</button></article>`}).join('');
  const currentKeys=new Set(totals.map(l=>l.key)),legacy=state.rows.filter(r=>connected(r)&&!currentKeys.has(r.lesson_key));const note=$('legacyNote');if(legacy.length){note.classList.remove('hidden');note.innerHTML=`<b>${legacy.length} legacy/unmapped video record${legacy.length===1?'':'s'} preserved.</b> They do not match the lesson keys in the current four-path Academy, so Admin leaves them untouched instead of guessing a mapping.`}else note.classList.add('hidden');
  document.querySelectorAll('.manage-course').forEach(b=>b.onclick=()=>openCourse(b.dataset.course));
}

function openCourse(id){const course=state.courses.find(c=>c.id===id);if(!course)return;state.course=course;state.filter='all';state.search='';$('lessonSearch').value='';document.querySelectorAll('.filter').forEach(b=>b.classList.toggle('active',b.dataset.filter==='all'));renderCourse();showView('course')}
function renderCourse(){const c=state.course;if(!c)return;const s=statsFor(c);$('courseTitle').textContent=c.title;$('courseSubtitle').textContent=`${s.total} lessons · ${s.done} connected · ${s.missing} missing`;$('courseSummary').innerHTML=`<div class="summary-copy"><b>${escapeHtml(c.short)} · ${escapeHtml(c.title)}</b><p>This list is generated from the same current Academy course source, not a separate curriculum.</p><div class="progress"><i style="width:${s.pct}%"></i></div></div><div class="summary-numbers"><span>${s.done} connected</span><span>${s.missing} missing</span><span>${s.pct}% complete</span></div>`;
  const q=state.search.toLowerCase().trim();const visible=c.lessons.filter(l=>{const ok=connected(rowFor(l.key));if(state.filter==='connected'&&!ok)return false;if(state.filter==='missing'&&ok)return false;return !q||l.title.toLowerCase().includes(q)||l.key.toLowerCase().includes(q)||l.moduleTitle.toLowerCase().includes(q)});const list=$('lessonList');if(!visible.length){list.innerHTML='<div class="empty">No lessons match this filter.</div>';return}list.innerHTML=visible.map(l=>{const r=rowFor(l.key),ok=connected(r);return`<article class="lesson-row"><div><div class="lesson-kicker">${escapeHtml(l.moduleTitle)}</div><div class="lesson-title">${escapeHtml(l.n?l.n+' · '+l.title:l.title)}</div><div class="lesson-key">${escapeHtml(l.key)}</div><div class="lesson-meta-line"><span>Duration: ${ok&&r.duration_sec!=null?fmtDuration(r.duration_sec):(l.dur||'—')}</span><span>Updated: ${ok?fmtDate(r.updated_at):'Never'}</span></div></div><div class="lesson-right"><span class="status-pill ${ok?'connected':'missing'}"><span class="status-dot"></span>${ok?'Video connected':'Missing video'}</span><div class="row-actions"><button class="mini-btn primary-mini" data-edit="${escapeHtml(l.key)}" type="button">${ok?'Edit':'Add video'}</button>${ok?`<button class="mini-btn" data-preview="${escapeHtml(l.key)}" type="button">Preview</button><button class="mini-btn danger-mini" data-remove="${escapeHtml(l.key)}" type="button">Remove</button>`:''}<button class="mini-btn" data-open-academy type="button">Open Academy</button></div></div></article>`}).join('');
  list.querySelectorAll('[data-edit]').forEach(b=>b.onclick=()=>openEditor(b.dataset.edit,'course'));list.querySelectorAll('[data-preview]').forEach(b=>b.onclick=()=>openPreview(b.dataset.preview));list.querySelectorAll('[data-remove]').forEach(b=>b.onclick=()=>removeVideo(b.dataset.remove));list.querySelectorAll('[data-open-academy]').forEach(b=>b.onclick=()=>window.open(ACADEMY_URL,'_blank','noopener'));
}

function findLesson(key){for(const c of state.courses){const l=c.lessons.find(x=>x.key===key);if(l)return{course:c,lesson:l}}return null}
function openEditor(key,returnView='course'){const found=findLesson(key);if(!found)return;state.course=found.course;state.lesson=found.lesson;state.returnView=returnView;const l=found.lesson,r=rowFor(l.key);$('editorHeading').textContent=connected(r)?'Edit lesson video':'Add lesson video';$('editorCourse').textContent=found.course.title;$('editorModule').textContent=l.moduleTitle;$('editorLesson').textContent=l.n?`${l.n} · ${l.title}`:l.title;$('editorKey').textContent=l.key;$('videoUrl').value=r?.url||'';$('videoDuration').value=r?.duration_sec!=null?fmtDuration(r.duration_sec):'';renderEditorStatus();renderEditorPreview();showView('editor')}
function renderEditorStatus(){const l=state.lesson;if(!l)return;const r=rowFor(l.key),ok=connected(r);$('currentStatus').innerHTML=ok?`<b>Connected.</b> Last updated ${escapeHtml(fmtDate(r.updated_at))}.`:'<b>Missing video.</b> Paste an unlisted YouTube link and save it.';$('removeVideoBtn').disabled=!ok}
function renderEditorPreview(){const box=$('editorPreview'),info=youtubeInfo($('videoUrl').value);box.innerHTML='';if(!info.ok){box.innerHTML='<div class="preview-copy"><b>Paste a valid YouTube link</b>Your vertical lesson preview appears here.</div>';return}const f=document.createElement('iframe');f.src=info.embed;f.title='Lesson video preview';f.loading='lazy';f.allow='accelerometer; autoplay; encrypted-media; picture-in-picture; fullscreen';f.setAttribute('allowfullscreen','');box.appendChild(f)}
async function saveEditor(){const l=state.lesson;if(!l)return;const info=youtubeInfo($('videoUrl').value);if(!info.ok){toast(info.error,true);return}const duration=parseDuration($('videoDuration').value);if(!duration.ok){toast(duration.error,true);return}const btn=$('saveVideoBtn');btn.disabled=true;btn.textContent='Saving…';try{const data=await adminApi('POST',{action:'upsert',lesson_key:l.key,url:info.canonical,duration_sec:duration.value});if(data.row){state.rowMap.set(data.row.lesson_key,data.row);state.rows=[...state.rowMap.values()]}$('videoUrl').value=data.row?.url||info.canonical;$('videoDuration').value=data.row?.duration_sec!=null?fmtDuration(data.row.duration_sec):'';renderEditorStatus();renderEditorPreview();renderDashboard();toast('Lesson video saved.')}catch(e){toast(e.message,true)}finally{btn.disabled=false;btn.textContent='Save Lesson Video'}}
async function removeVideo(key=state.lesson?.key){if(!key)return;const found=findLesson(key),title=found?.lesson?.title||key;if(!confirm(`Remove the video from “${title}”? The lesson itself will stay in Academy.`))return;try{const data=await adminApi('POST',{action:'clear',lesson_key:key});if(data.row){state.rowMap.set(data.row.lesson_key,data.row);state.rows=[...state.rowMap.values()]}renderDashboard();if(state.course)renderCourse();if(state.lesson?.key===key){$('videoUrl').value='';$('videoDuration').value='';renderEditorStatus();renderEditorPreview()}toast('Video removed.')}catch(e){toast(e.message,true)}}
function openPreview(key){const found=findLesson(key),r=rowFor(key);if(!found||!connected(r))return;const info=youtubeInfo(r.url);if(!info.ok){toast('This saved URL is not a supported YouTube link.',true);return}$('dialogTitle').textContent=found.lesson.title;$('dialogPlayer').innerHTML=`<iframe src="${info.embed}" title="${escapeHtml(found.lesson.title)}" allow="accelerometer; autoplay; encrypted-media; picture-in-picture; fullscreen" allowfullscreen></iframe>`;$('previewDialog').showModal()}

function openBulk(courseId=state.course?.id||state.courses[0]?.id){$('bulkCourse').innerHTML=state.courses.map(c=>`<option value="${c.id}">${escapeHtml(c.title)}</option>`).join('');if(courseId)$('bulkCourse').value=courseId;renderBulk();showView('bulk')}
function renderBulk(){const course=state.courses.find(c=>c.id===$('bulkCourse').value)||state.courses[0];state.course=course;const list=$('bulkList');list.innerHTML=course.lessons.map(l=>{const r=rowFor(l.key),url=r?.url||'',dur=r?.duration_sec!=null?fmtDuration(r.duration_sec):'';return`<div class="bulk-row" data-bulk-key="${escapeHtml(l.key)}" data-initial-url="${escapeHtml(url)}" data-initial-duration="${escapeHtml(String(r?.duration_sec??''))}"><div class="bulk-name"><b>${escapeHtml(l.n?l.n+' · '+l.title:l.title)}</b><span>${escapeHtml(l.key)}</span></div><input class="bulk-url" type="url" inputmode="url" value="${escapeHtml(url)}" placeholder="Paste YouTube URL"><input class="bulk-duration" inputmode="numeric" value="${escapeHtml(dur)}" placeholder="09:32"></div>`}).join('');$('bulkStatus').textContent=`${course.lessons.length} lessons · existing URLs are prefilled · blank missing lessons are ignored.`}
async function saveBulk(){const rows=[...$('bulkList').querySelectorAll('.bulk-row')];const items=[];let invalid='';rows.forEach(row=>row.classList.remove('invalid'));for(const row of rows){const key=row.dataset.bulkKey,urlInput=row.querySelector('.bulk-url'),durInput=row.querySelector('.bulk-duration'),raw=urlInput.value.trim(),initialUrl=row.dataset.initialUrl||'',initialDuration=row.dataset.initialDuration||'';if(!raw)continue;const info=youtubeInfo(raw);if(!info.ok){row.classList.add('invalid');invalid=`${key}: ${info.error}`;break}const duration=parseDuration(durInput.value);if(!duration.ok){row.classList.add('invalid');invalid=`${key}: ${duration.error}`;break}const initialInfo=initialUrl?youtubeInfo(initialUrl):null;const sameUrl=initialInfo?.ok?initialInfo.id===info.id:false;const nextDur=duration.value===null?'':String(duration.value);if(sameUrl&&nextDur===initialDuration)continue;items.push({lesson_key:key,url:info.canonical,duration_sec:duration.value})}if(invalid){toast(invalid,true);return}if(!items.length){toast('No new or changed video links to save.');return}const btn=$('bulkSaveBtn');btn.disabled=true;btn.textContent=`Saving ${items.length}…`;try{const data=await adminApi('POST',{action:'bulk_upsert',items});(data.rows||[]).forEach(r=>state.rowMap.set(r.lesson_key,r));state.rows=[...state.rowMap.values()];renderDashboard();renderBulk();toast(`${data.count||items.length} video${items.length===1?'':'s'} saved.`)}catch(e){toast(e.message,true)}finally{btn.disabled=false;btn.textContent='Save all videos'}}

function bind(){
  $('loginBtn').onclick=signIn;$('loginPassword').addEventListener('keydown',e=>{if(e.key==='Enter')signIn()});$('deniedSignOut').onclick=signOut;$('signOutBtn').onclick=signOut;
  $('refreshBtn').onclick=async()=>{try{await loadLibrary();toast('Video library refreshed.')}catch(e){toast(e.message,true)}};$('dashboardBulkBtn').onclick=()=>openBulk(state.courses[0]?.id);$('courseBack').onclick=()=>{renderDashboard();showView('dashboard')};$('courseBulkBtn').onclick=()=>openBulk(state.course?.id);
  $('lessonSearch').oninput=e=>{state.search=e.target.value;renderCourse()};document.querySelectorAll('.filter').forEach(b=>b.onclick=()=>{state.filter=b.dataset.filter;document.querySelectorAll('.filter').forEach(x=>x.classList.toggle('active',x===b));renderCourse()});
  $('editorBack').onclick=()=>{if(state.returnView==='bulk'){renderBulk();showView('bulk')}else{renderCourse();showView('course')}};$('videoUrl').oninput=renderEditorPreview;$('saveVideoBtn').onclick=saveEditor;$('removeVideoBtn').onclick=()=>removeVideo();$('openAcademyBtn').onclick=()=>window.open(ACADEMY_URL,'_blank','noopener');
  $('bulkBack').onclick=()=>{if(state.course){renderCourse();showView('course')}else showView('dashboard')};$('bulkCourse').onchange=renderBulk;$('bulkRefresh').onclick=renderBulk;$('bulkSaveBtn').onclick=saveBulk;
  $('dialogClose').onclick=()=>$('previewDialog').close();$('previewDialog').addEventListener('close',()=>{$('dialogPlayer').innerHTML=''});
  sb.auth.onAuthStateChange((event,session)=>{state.session=session;if(event==='SIGNED_OUT')showAuth('login')});
}

bind();bootstrapSession();
})();
