(()=>{
'use strict';
const SUPABASE_URL='https://rgbweaimkcndjznlazho.supabase.co';
const SUPABASE_KEY='sb_publishable_S3IEOR8vkWkXEdGtx8fGjw_nH8c4fV3';
const sb=window.supabase.createClient(SUPABASE_URL,SUPABASE_KEY,{auth:{persistSession:true,autoRefreshToken:true,detectSessionInUrl:true}});
const $=id=>document.getElementById(id);
const STATUS=[
 {key:'all',label:'All'},
 {key:'new',label:'New'},
 {key:'qualified',label:'Qualified'},
 {key:'sample_ready',label:'Sample Ready'},
 {key:'pitched',label:'Pitched'},
 {key:'follow_up',label:'Follow-up'},
 {key:'won',label:'Won'},
 {key:'lost',label:'Lost'}
];
const PIPE=STATUS.slice(1);
const state={session:null,rows:[],filter:'all',search:'',editing:null};
const SERVICE_BY_SKILL={design:'Design & Flyers',video:'AI UGC & Influencer',landing:'Landing Page Design',money:''};
const ENTRY=(()=>{const p=new URLSearchParams(location.search);return{from:p.get('from')||'',skill:p.get('skill')||'',sprint:p.get('sprint')||''}})();
let entryApplied=false;
let toastTimer;
function esc(v){return String(v??'').replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]))}
function toast(msg,bad=false){const e=$('toast');e.textContent=msg;e.className='toast show'+(bad?' bad':'');clearTimeout(toastTimer);toastTimer=setTimeout(()=>e.className='toast',2800)}
function labelStatus(k){return PIPE.find(x=>x.key===k)?.label||k}
function money(r){if(r.offer_price===null||r.offer_price===undefined||r.offer_price==='')return'';const cur=r.offer_currency||'NGN',n=Number(r.offer_price);try{return new Intl.NumberFormat(cur==='NGN'?'en-NG':'en-US',{style:'currency',currency:cur,maximumFractionDigits:0}).format(n)}catch{return cur+' '+n.toLocaleString()}}
function fmtDate(v,short=false){if(!v)return'';const d=new Date(v);if(Number.isNaN(d.getTime()))return'';return d.toLocaleString([],short?{month:'short',day:'numeric',hour:'2-digit',minute:'2-digit'}:{year:'numeric',month:'short',day:'numeric',hour:'2-digit',minute:'2-digit'})}
function localValue(v){if(!v)return'';const d=new Date(v);if(Number.isNaN(d.getTime()))return'';const p=n=>String(n).padStart(2,'0');return `${d.getFullYear()}-${p(d.getMonth()+1)}-${p(d.getDate())}T${p(d.getHours())}:${p(d.getMinutes())}`}
function due(r){if(!r.next_follow_up||['won','lost'].includes(r.status))return false;return new Date(r.next_follow_up).getTime()<=Date.now()}
function normalizeUrl(v){const s=String(v||'').trim();if(!s)return'';try{return new URL(/^https?:\/\//i.test(s)?s:'https://'+s).href}catch{return''}}
function whatsappUrl(v){const d=String(v||'').replace(/\D/g,'');return d?`https://wa.me/${d}`:''}
function instagramUrl(v){const s=String(v||'').trim();if(!s)return'';if(/^https?:\/\//i.test(s))return s;return `https://instagram.com/${s.replace(/^@/,'')}`}

async function getSession(){const{data,error}=await sb.auth.getSession();if(error)throw error;return data.session||null}
function showAuth(msg=''){$('authView').classList.remove('hidden');$('app').classList.add('hidden');$('loginMessage').textContent=msg}
function showApp(){$('authView').classList.add('hidden');$('app').classList.remove('hidden')}
async function signIn(){const email=$('loginEmail').value.trim(),password=$('loginPassword').value;if(!email||!password)return showAuth('Enter your email and password.');$('loginBtn').disabled=true;$('loginBtn').textContent='Signing in…';try{const{data,error}=await sb.auth.signInWithPassword({email,password});if(error)throw error;state.session=data.session;showApp();await load();applyEntryContext()}catch(e){showAuth(e.message||'Could not sign in.')}finally{$('loginBtn').disabled=false;$('loginBtn').textContent='Sign in'}}
async function boot(){try{state.session=await getSession();if(!state.session)return showAuth();$('accountEmail').textContent=state.session.user.email||'Fuse user';showApp();await load();applyEntryContext()}catch(e){showAuth(e.message||'Could not start Fuse Clients.')}}

async function load(){const{data,error}=await sb.from('client_prospects').select('*').order('updated_at',{ascending:false});if(error){if(/JWT|auth|session/i.test(error.message||''))return showAuth('Your session expired. Sign in again.');toast(error.message||'Could not load prospects.',true);return}state.rows=data||[];render()}
function counts(){const out={all:state.rows.length};PIPE.forEach(s=>out[s.key]=state.rows.filter(r=>r.status===s.key).length);return out}
function wonValue(){return state.rows.filter(r=>r.status==='won').reduce((a,r)=>a+(Number(r.offer_price)||0),0)}
function renderStats(){const c=counts(),dueN=state.rows.filter(due).length,pitched=(c.pitched||0)+(c.follow_up||0)+(c.won||0);$('stats').innerHTML=`<div class="stat"><b>${c.all}</b><span>Total prospects</span></div><div class="stat"><b>${pitched}</b><span>Pitched / beyond</span></div><div class="stat"><b>${dueN}</b><span>Follow-ups due</span></div><div class="stat"><b>${c.won||0}</b><span>Clients won</span></div>`;const sprint=Math.min(c.all,50),pct=Math.round(sprint/50*100);$('sprintText').textContent=c.all?`${sprint} / 50 prospects added · ${pct}% of your Money Engine list.`:'Add your first prospect to begin.'}
function renderPipeline(){const c=counts();$('pipeline').innerHTML=PIPE.map(s=>`<button class="stage ${state.filter===s.key?'active':''}" data-stage="${s.key}" type="button"><i></i><b>${c[s.key]||0}</b><span>${esc(s.label)}</span></button>`).join('');$('pipeline').querySelectorAll('[data-stage]').forEach(b=>b.onclick=()=>{state.filter=state.filter===b.dataset.stage?'all':b.dataset.stage;syncFilterButtons();renderPipeline();renderList()})}
function renderFilters(){const c=counts();$('filters').innerHTML=STATUS.map(s=>`<button class="filter ${state.filter===s.key?'active':''}" data-filter="${s.key}" type="button">${esc(s.label)}${s.key!=='all'&&c[s.key]?` · ${c[s.key]}`:''}</button>`).join('');$('filters').querySelectorAll('[data-filter]').forEach(b=>b.onclick=()=>{state.filter=b.dataset.filter;syncFilterButtons();renderPipeline();renderList()})}
function syncFilterButtons(){document.querySelectorAll('[data-filter]').forEach(b=>b.classList.toggle('active',b.dataset.filter===state.filter))}
function renderToday(){const rows=state.rows.filter(due).sort((a,b)=>new Date(a.next_follow_up)-new Date(b.next_follow_up));$('todayBox').innerHTML=`<div class="today-top"><b>Today’s move</b><span>${rows.length?rows.length+' FOLLOW-UP'+(rows.length===1?'':'S')+' DUE':'CLEAR'}</span></div>${rows.length?`<div class="today-list">${rows.slice(0,5).map(r=>`<div class="today-row"><div><b>${esc(r.brand_name)}</b><small>${esc(r.contact_name||r.niche||'Prospect')} · due ${esc(fmtDate(r.next_follow_up,true))}</small></div><button class="mini hot" data-today="${r.id}" type="button">Open →</button></div>`).join('')}</div>`:'<div class="today-empty">No overdue follow-ups. Keep adding qualified prospects or move your latest pitch forward.</div>'}`;$('todayBox').querySelectorAll('[data-today]').forEach(b=>b.onclick=()=>openEditor(b.dataset.today))}
function filtered(){const q=state.search.toLowerCase().trim();return state.rows.filter(r=>{if(state.filter!=='all'&&r.status!==state.filter)return false;if(!q)return true;return [r.brand_name,r.niche,r.location,r.contact_name,r.email,r.whatsapp,r.visible_problem,r.service,r.source].some(v=>String(v||'').toLowerCase().includes(q))})}
function renderList(){const rows=filtered();$('resultCount').textContent=`${rows.length} prospect${rows.length===1?'':'s'}`;const root=$('prospects');if(!rows.length){root.innerHTML=`<div class="empty"><b>${state.rows.length?'No prospects match this view.':'Your pipeline is empty.'}</b>${state.rows.length?'Try another filter or search term.':'Add the first brand you want to pitch and start your 50-prospect sprint.'}</div>`;return}root.innerHTML=rows.map(r=>{const m=money(r),isDue=due(r);return`<article class="prospect"><div><h3>${esc(r.brand_name)}</h3><div class="prospect-sub">${esc([r.niche,r.location,r.contact_name].filter(Boolean).join(' · ')||'Prospect')}</div><div class="chips"><span class="chip status">${esc(labelStatus(r.status))}</span>${r.service?`<span class="chip">${esc(r.service)}</span>`:''}${r.source?`<span class="chip">${esc(r.source)}</span>`:''}${isDue?`<span class="chip due">Follow-up due</span>`:''}</div>${r.visible_problem?`<div class="problem">${esc(r.visible_problem)}</div>`:''}</div><div class="prospect-right">${m?`<div class="money">${esc(m)}</div>`:''}<div class="quick"><button class="mini" data-open="${r.id}" type="button">Open</button>${r.status==='new'?`<button class="mini hot" data-status-id="${r.id}" data-status="qualified" type="button">Qualify</button>`:''}${r.status==='qualified'?`<button class="mini hot" data-status-id="${r.id}" data-status="sample_ready" type="button">Sample ready</button>`:''}${r.status==='sample_ready'?`<button class="mini hot" data-status-id="${r.id}" data-status="pitched" type="button">Mark pitched</button>`:''}${r.status==='pitched'?`<button class="mini hot" data-status-id="${r.id}" data-status="follow_up" type="button">Follow-up</button>`:''}${r.status==='follow_up'?`<button class="mini hot" data-status-id="${r.id}" data-status="won" type="button">Won ✓</button>`:''}</div></div></article>`}).join('');root.querySelectorAll('[data-open]').forEach(b=>b.onclick=()=>openEditor(b.dataset.open));root.querySelectorAll('[data-status-id]').forEach(b=>b.onclick=()=>quickStatus(b.dataset.statusId,b.dataset.status))}
function render(){renderStats();renderPipeline();renderFilters();renderToday();renderList()}

function clearForm(){state.editing=null;$('editorTitle').textContent='Add prospect';$('editorSub').textContent='Capture enough context to pitch intelligently.';$('deleteBtn').classList.add('hidden');$('contactActions').classList.add('hidden');$('contactActions').innerHTML='';['fBrand','fNiche','fLocation','fContact','fEmail','fWhatsapp','fInstagram','fWebsite','fPrice','fProblem','fSample','fFollowup','fNotes'].forEach(id=>$(id).value='');$('fStatus').value='new';$('fSource').value='';$('fService').value='';$('fCurrency').value='NGN'}
function openNew(){clearForm();openOverlay()}
function applyEntryContext(){
 if(entryApplied||ENTRY.from!=='academy')return;
 entryApplied=true;
 openNew();
 if(ENTRY.skill==='money'||ENTRY.sprint==='50'){
   $('editorTitle').textContent='Add prospect · 50-lead sprint';
   $('editorSub').textContent='Start the Money Engine with one qualified prospect. Keep going until you reach 50.';
   $('fSource').value='Google Maps';
   toast('Money Engine sprint started. Add prospect 1 of 50.');
 }else{
   const service=SERVICE_BY_SKILL[ENTRY.skill]||'';
   if(service&&[...$('fService').options].some(o=>o.value===service||o.textContent===service))$('fService').value=service;
   $('editorTitle').textContent=service?`Find clients for ${service}`:'Add prospect';
   $('editorSub').textContent=service?'This prospect is starting from the skill you came from in Academy.':'Capture enough context to pitch intelligently.';
   if(service)toast(`${service} selected. Add the first brand you want to pitch.`);
 }
 try{history.replaceState({},'',location.pathname)}catch(_){}
}
function openEditor(id){const r=state.rows.find(x=>x.id===id);if(!r)return;state.editing=r.id;$('editorTitle').textContent=r.brand_name;$('editorSub').textContent=`${labelStatus(r.status)} · updated ${fmtDate(r.updated_at,true)}`;$('deleteBtn').classList.remove('hidden');$('fBrand').value=r.brand_name||'';$('fStatus').value=r.status||'new';$('fNiche').value=r.niche||'';$('fLocation').value=r.location||'';$('fContact').value=r.contact_name||'';$('fSource').value=r.source||'';$('fEmail').value=r.email||'';$('fWhatsapp').value=r.whatsapp||'';$('fInstagram').value=r.instagram||'';$('fWebsite').value=r.website||'';$('fService').value=r.service||'';$('fCurrency').value=r.offer_currency||'NGN';$('fPrice').value=r.offer_price??'';$('fProblem').value=r.visible_problem||'';$('fSample').value=r.sample_url||'';$('fFollowup').value=localValue(r.next_follow_up);$('fNotes').value=r.notes||'';renderContactActions(r);openOverlay()}
function renderContactActions(r){const actions=[],wa=whatsappUrl(r.whatsapp),site=normalizeUrl(r.website),ig=instagramUrl(r.instagram),sample=normalizeUrl(r.sample_url);if(wa)actions.push(`<a class="primary-link" href="${esc(wa)}" target="_blank" rel="noopener">WhatsApp</a>`);if(r.email)actions.push(`<a href="mailto:${esc(r.email)}">Email</a>`);if(ig)actions.push(`<a href="${esc(ig)}" target="_blank" rel="noopener">Instagram</a>`);if(site)actions.push(`<a href="${esc(site)}" target="_blank" rel="noopener">Website</a>`);if(sample)actions.push(`<a href="${esc(sample)}" target="_blank" rel="noopener">Open sample</a>`);$('contactActions').innerHTML=actions.join('');$('contactActions').classList.toggle('hidden',!actions.length)}
function openOverlay(){$('editorOverlay').classList.add('open');$('editorOverlay').setAttribute('aria-hidden','false');document.body.style.overflow='hidden';setTimeout(()=>$('fBrand').focus(),80)}
function closeOverlay(){$('editorOverlay').classList.remove('open');$('editorOverlay').setAttribute('aria-hidden','true');document.body.style.overflow=''}
function payload(){const price=$('fPrice').value.trim();return{brand_name:$('fBrand').value.trim(),status:$('fStatus').value,niche:$('fNiche').value.trim()||null,location:$('fLocation').value.trim()||null,contact_name:$('fContact').value.trim()||null,source:$('fSource').value||null,email:$('fEmail').value.trim()||null,whatsapp:$('fWhatsapp').value.trim()||null,instagram:$('fInstagram').value.trim()||null,website:$('fWebsite').value.trim()||null,service:$('fService').value||null,offer_currency:$('fCurrency').value||'NGN',offer_price:price===''?null:Number(price),visible_problem:$('fProblem').value.trim()||null,sample_url:$('fSample').value.trim()||null,next_follow_up:$('fFollowup').value?new Date($('fFollowup').value).toISOString():null,notes:$('fNotes').value.trim()||null}}
async function save(){const p=payload();if(!p.brand_name)return toast('Add the brand or business name.',true);if(p.offer_price!==null&&(!Number.isFinite(p.offer_price)||p.offer_price<0))return toast('Check the offer price.',true);$('saveBtn').disabled=true;$('saveBtn').textContent='Saving…';try{let q;if(state.editing)q=sb.from('client_prospects').update(p).eq('id',state.editing).select().single();else q=sb.from('client_prospects').insert({...p,user_id:state.session.user.id}).select().single();const{data,error}=await q;if(error)throw error;if(state.editing)state.rows=state.rows.map(r=>r.id===data.id?data:r);else state.rows.unshift(data);closeOverlay();render();toast(state.editing?'Prospect updated.':'Prospect added to your pipeline.')}catch(e){toast(e.message||'Could not save prospect.',true)}finally{$('saveBtn').disabled=false;$('saveBtn').textContent='Save prospect'}}
async function remove(){if(!state.editing)return;const r=state.rows.find(x=>x.id===state.editing);if(!confirm(`Delete ${r?.brand_name||'this prospect'} from your pipeline?`))return;$('deleteBtn').disabled=true;try{const{error}=await sb.from('client_prospects').delete().eq('id',state.editing);if(error)throw error;state.rows=state.rows.filter(x=>x.id!==state.editing);closeOverlay();render();toast('Prospect deleted.')}catch(e){toast(e.message||'Could not delete prospect.',true)}finally{$('deleteBtn').disabled=false}}
async function quickStatus(id,status){const patch={status};if(status==='pitched'&&!state.rows.find(x=>x.id===id)?.next_follow_up){const d=new Date();d.setDate(d.getDate()+3);patch.next_follow_up=d.toISOString()}if(status==='won'||status==='lost')patch.next_follow_up=null;try{const{data,error}=await sb.from('client_prospects').update(patch).eq('id',id).select().single();if(error)throw error;state.rows=state.rows.map(r=>r.id===id?data:r);render();toast(`Moved to ${labelStatus(status)}.`)}catch(e){toast(e.message||'Could not update status.',true)}}

$('loginBtn').onclick=signIn;$('loginPassword').addEventListener('keydown',e=>{if(e.key==='Enter')signIn()});$('addTopBtn').onclick=openNew;$('addHeroBtn').onclick=openNew;$('closeEditor').onclick=closeOverlay;$('cancelBtn').onclick=closeOverlay;$('saveBtn').onclick=save;$('deleteBtn').onclick=remove;$('refreshBtn').onclick=async()=>{await load();toast('Pipeline refreshed.')};$('editorOverlay').addEventListener('click',e=>{if(e.target===$('editorOverlay'))closeOverlay()});$('searchInput').addEventListener('input',e=>{state.search=e.target.value;renderList()});document.querySelectorAll('[data-href]').forEach(b=>b.onclick=()=>{location.href=b.dataset.href});document.addEventListener('keydown',e=>{if(e.key==='Escape'&&$('editorOverlay').classList.contains('open'))closeOverlay()});
boot();
})();