(() => {
'use strict';
const $=id=>document.getElementById(id),params=new URLSearchParams(location.search),key=params.get('course');
const course=key==='money'?window.FUSE_ACADEMY_MONEY:window.FUSE_COURSE?.pillars.find(p=>p.key===key);
if(!course){location.replace('learn.html');return}
const lessons=course.modules.flatMap(m=>m.lessons.map(l=>({...l,module:m.title})));
let index=-1,requestVersion=0;
$('courseTitle').textContent=key==='money'?'Money Engine 01':course.name;
function embedUrl(raw){const u=new URL(raw);if(u.protocol!=='https:')throw Error('This video link is unavailable.');const host=u.hostname.replace(/^www\./,'');let id;if(host==='youtu.be')id=u.pathname.split('/')[1];else if(['youtube.com','m.youtube.com','youtube-nocookie.com'].includes(host)){id=u.searchParams.get('v')||u.pathname.split('/').filter(Boolean).at(-1)}if(id&&/^[A-Za-z0-9_-]{6,20}$/.test(id))return 'https://www.youtube-nocookie.com/embed/'+id+'?rel=0&playsinline=1';if(host==='drive.google.com'){const match=u.pathname.match(/\/file\/d\/([^/]+)/);const driveId=match?.[1]||u.searchParams.get('id');if(driveId&&/^[A-Za-z0-9_-]+$/.test(driveId))return 'https://drive.google.com/file/d/'+driveId+'/preview'}return null}
function draw(){const nodes=lessons.map((l,i)=>{const b=document.createElement('button');b.className='lesson-item';b.setAttribute('aria-current',i===index?'true':'false');const n=document.createElement('span');n.className='lesson-number';n.textContent=String(i+1).padStart(2,'0');const title=document.createElement('span');title.textContent=l.title;b.append(n,title);b.onclick=()=>open(i);return b});$('lessonsPanel').replaceChildren(...nodes)}
async function open(i){index=i;const version=++requestVersion,lesson=lessons[i];draw();$('lessonTitle').textContent=lesson.title;$('nextLesson').disabled=i>=lessons.length-1;$('lessonPlayer').replaceChildren();$('lessonStatus').textContent='Loading lesson…';$('retryLesson').hidden=true;$('notesPanel').textContent='Open an available lesson to view its notes.';history.replaceState(null,'','?course='+encodeURIComponent(key)+'&lesson='+encodeURIComponent(lesson.key));try{const data=await Fuse.api('lesson-video',{lesson_key:lesson.key});if(version!==requestVersion)return;const embed=embedUrl(data.url);let media;if(embed){media=document.createElement('iframe');media.src=embed;media.title=lesson.title;media.allow='autoplay; fullscreen; picture-in-picture';media.allowFullscreen=true;media.referrerPolicy='strict-origin-when-cross-origin'}else{media=document.createElement('video');media.src=data.url;media.controls=true;media.playsInline=true;media.preload='metadata';media.addEventListener('error',()=>{$('lessonStatus').textContent='This video could not load. Try again.';$('retryLesson').hidden=false})}$('lessonPlayer').append(media);$('lessonStatus').textContent='';if(lesson.notes){$('notesPanel').innerHTML=lesson.notes;$('notesPanel').querySelectorAll('a[target="_blank"]').forEach(a=>a.rel='noopener noreferrer')}else $('notesPanel').textContent='No additional notes for this lesson.'}catch(e){if(version!==requestVersion)return;$('lessonStatus').textContent=e.message;$('retryLesson').hidden=false}}
document.querySelectorAll('[data-lesson-tab]').forEach(b=>b.onclick=()=>{document.querySelectorAll('[data-lesson-tab]').forEach(t=>{const active=t===b;t.classList.toggle('active',active);t.setAttribute('aria-pressed',String(active))});['lessons','notes','resources'].forEach(t=>$(t+'Panel').hidden=t!==b.dataset.lessonTab)});
$('retryLesson').onclick=()=>open(index);$('nextLesson').onclick=()=>{if(index<lessons.length-1){open(index+1);window.scrollTo({top:0,behavior:'smooth'})}};
const selected=lessons.findIndex(l=>l.key===params.get('lesson'));draw();open(selected<0?0:selected);
})();
