(() => {'use strict';const $=id=>document.getElementById(id);let config,type=['image','video','audio'].includes(new URLSearchParams(location.search).get('type'))?new URLSearchParams(location.search).get('type'):'image',busy=false,quoted=null,quoteVersion=0,timer;
function message(text,error=false){$('studioStatus').textContent=text;$('studioStatus').classList.toggle('error',error)}
function payload(){return{type,model:$('model').value,prompt:$('prompt').value,aspect:$('aspect').value,duration:$('duration').value,voice_sample_url:$('voiceUrl').value,reference_text:$('referenceText').value,voice_consent:$('consent').checked}}
function choices(el,values){el.replaceChildren(...values.map(value=>{const option=document.createElement('option');option.value=typeof value==='string'?value:value.id;option.textContent=typeof value==='string'?value:value.label;return option}))}
function settings(){const model=config[type].find(m=>m.id===$('model').value);choices($('aspect'),model.aspects||[]);choices($('duration'),model.durations||[]);quote()}
function mode(value){if(busy)return;type=value;document.querySelectorAll('[data-type]').forEach(b=>{b.classList.toggle('active',b.dataset.type===type);b.setAttribute('aria-pressed',String(b.dataset.type===type))});choices($('model'),config[type]);$('model').disabled=false;$('voiceSettings').hidden=type!=='audio';$('voiceUrl').required=type==='audio';$('consent').required=type==='audio';$('visualSettings').hidden=type==='audio';$('durationField').hidden=type!=='video';$('promptLabel').textContent=type==='audio'?'Script':'Prompt';settings()}
async function quote(){const version=++quoteVersion;quoted=null;$('generate').disabled=true;if(!config?.generationConfigured){$('generate').textContent='Generation unavailable';message('WaveSpeed is not configured for this deployment.',true);return}if(!$('prompt').value.trim()){$('generate').textContent='Add a prompt to see cost';return}try{const q=await Fuse.api('studio-generate',{...payload(),quote:true});if(version!==quoteVersion)return;quoted=q.credits;$('generate').textContent=`Generate · ${quoted} credits`;$('generate').disabled=busy;message('')}catch(e){if(version===quoteVersion)message(e.message,true)}}
function resultNode(job){const card=document.createElement('article');card.className='result';const p=document.createElement('p');p.textContent=job.status==='processing'?'Generating…':job.status==='failed'?'Generation failed. Check your credit balance.':job.prompt||'Your creation';card.append(p);if(job.status==='completed'&&job.output_url){try{const url=new URL(job.output_url);if(url.protocol!=='https:')return card;const media=document.createElement(job.kind==='video'?'video':job.kind==='audio'?'audio':'img');media.src=url.href;if(media.tagName==='IMG'){media.alt=job.prompt||'Generated image';media.loading='lazy'}else{media.controls=true;media.preload='metadata';media.playsInline=true}const link=document.createElement('a');link.href=url.href;link.target='_blank';link.rel='noopener noreferrer';link.textContent='Open / save result';card.prepend(media);card.append(link)}catch{p.textContent='The result link is unavailable.'}}return card}
async function history(){try{const sb=await Fuse.client(),session=await Fuse.session();const{data,error}=await sb.from('jobs').select('request_id,kind,prompt,status,output_url,created_at').eq('user_id',session.user.id).in('kind',['image','video','audio']).order('created_at',{ascending:false}).limit(20);if(error)throw error;if(data.length)$('results').replaceChildren(...data.map(resultNode));else $('results').innerHTML='<div class="panel muted">Your results will appear here.</div>';return data}catch(e){message(e.message,true);return[]}}
async function poll(id){for(let i=0;i<180;i++){if(document.hidden){await new Promise(r=>setTimeout(r,5000));continue}await new Promise(r=>setTimeout(r,4000));try{const result=await Fuse.api('job-status?id='+encodeURIComponent(id));if(result.status!=='processing'){await history();await Fuse.balance();message(result.status==='failed'?(result.error||'Generation failed. Check your credit balance.'):'Your creation is ready.',result.status==='failed');return}}catch(e){message('The connection was interrupted. Use Refresh to check your saved job.',true);return}}message('This job is taking longer. Use Refresh to check its progress. No new request will be charged.')}
$('generateForm').onsubmit=async e=>{e.preventDefault();if(busy||quoted===null)return;busy=true;$('generate').disabled=true;const request={...payload(),accepted_credits:quoted};message('Starting your creation…');try{const result=await Fuse.api('studio-generate',request);await Fuse.balance();await history();if(result.request_id){message('Generating. You can return here to check your results.');void poll(result.request_id)}else message('The server returned no job ID. Check history before retrying.',true)}catch(err){message(err.message+' If the connection timed out, check history before trying again.',true)}finally{busy=false;$('generate').disabled=quoted===null}};
$('model').onchange=settings;$('aspect').onchange=quote;$('duration').onchange=quote;$('prompt').oninput=()=>{quoted=null;$('generate').disabled=true;clearTimeout(timer);timer=setTimeout(quote,500)};$('refreshResults').onclick=async()=>{const jobs=await history();const pending=jobs.filter(j=>j.status==='processing');for(const j of pending){try{await Fuse.api('job-status?id='+encodeURIComponent(j.request_id))}catch(e){message(e.message,true)}}await history();await Fuse.balance().catch(()=>{})};document.querySelectorAll('[data-type]').forEach(b=>b.onclick=()=>mode(b.dataset.type));
async function boot(){try{const response=await fetch('/api/studio-config',{signal:AbortSignal.timeout(15000)});if(!response.ok)throw Error('Generation settings could not load. Reload to try again.');config=await response.json();mode(type);await history()}catch(e){message(e.message,true);$('generate').textContent='Settings unavailable'}}boot();})();
