-- ============================================================
-- Fuse Studio — Phase 30: Flyer Studio "Spot Fix" tool.
-- flyer-spot-fix.js crops a marked region out of the current final flyer,
-- sends just that crop to GPT Image 2 for a targeted edit, and needs the
-- crop's exact pixel position + the original full image to paste the
-- result back into once the async job completes (job-status.js). jobs.meta
-- carries that (region + original_url) across the submit -> poll gap --
-- generic jsonb so any future job kind needing small structured extras can
-- reuse it instead of adding another single-purpose column.
-- ============================================================
alter table public.jobs add column if not exists meta jsonb;
