-- ============================================================
-- Fuse Studio — Phase 26: stop conflating "Studio subscription" with
-- "bonus plan from an Atelier course purchase".
--
-- profiles.plan = 'creator' currently gets written by TWO different
-- events: (1) actually buying the Studio Creator monthly subscription
-- (creator_mo), and (2) buying the Atelier Creator COURSE tier
-- (atelier_creator), which also grants a free month of the matching
-- plan as a bonus (see paystack-webhook.js step 4c). Same for 'pro'
-- (pro_mo vs atelier_empire). Looking at `profiles.plan` alone can no
-- longer tell you WHY someone has that value -- which is exactly what
-- made a legitimate Atelier Creator course buyer (who correctly has
-- both course access AND a plan bump) look, at a glance, like a
-- Studio-plan-only buyer who'd somehow also gotten course access.
--
-- plan_source records which one actually happened, going forward.
-- ============================================================
alter table public.profiles add column if not exists plan_source text; -- 'subscription' | 'course_bonus' | 'admin_grant' | null
