-- ============================================================
-- Fuse Studio — Phase 19: Flyer Studio aspect persistence.
--   GPT Image 2 (Flyer Studio's image model as of 2026-07-16, routed via
--   WaveSpeed) has no "auto/keep-current-aspect" option unlike nano-banana
--   — every generation call must pass a real aspect_ratio enum value. Layer
--   edits (flyer-layer.js) need to know the project's chosen aspect so they
--   don't silently reshape the working hero image; previously this only
--   ever lived on the `jobs` row for the original flyer-hero call, which
--   flyer-layer.js has no reason to look up. Persisting it directly on the
--   project is simpler and survives regardless of job history.
-- Run after earlier files. Safe to re-run.
-- ============================================================
alter table public.flyer_projects add column if not exists aspect text not null default '4:5';
