-- ============================================================
-- Fuse Studio — Phase 13: log failed generation attempts.
--   Free/paid users hitting a real engine failure (MuAPI 4xx/5xx,
--   timeout, etc.) were refunded correctly, but the failure itself
--   left no trace anywhere — impossible to diagnose after the fact.
--   This adds a place to record the actual error text so the next
--   failure is diagnosable from the DB instead of guesswork.
-- Run after earlier files. Safe to re-run. (Applied directly via
-- Supabase MCP on 2026-07-08 — this file just documents it.)
-- ============================================================
alter table public.jobs add column if not exists error_message text;
