-- ============================================================
-- Fuse Studio — Phase 21: voice-clone accuracy fix.
--   WaveSpeed's Omnivoice docs (checked 2026-07-17) confirm an optional
--   `reference_text` field — the exact transcript of the reference audio
--   clip — which "significantly improves cloning accuracy". The app never
--   collected or sent this, which is a real contributor to cloned voices
--   drifting away from the speaker's actual accent. This column lets an
--   avatar's own attached voice sample carry that transcript too (the
--   standalone `voices` table already gained its own `reference_text`
--   column in schema-phase20.sql).
-- Run after schema-phase20.sql. Safe to re-run.
-- ============================================================
alter table public.avatars add column if not exists voice_reference_text text;
