// ============================================================
// Fuse Atelier 2.0 — course data. Six skill families, three tiers.
//   pillar.tier: 'starter' | 'creator' | 'empire' — the minimum tier
//   that unlocks every module in that pillar (checked in app.js).
//   Lesson keys that already have uploaded videos in course_videos are
//   PRESERVED from the old structure (orient-*, spark-*, gold-3_5) so
//   nothing needs re-linking, EXCEPT Skill 1 (Social Media & Event
//   Flyers, the "design" pillar's flyer-m1..flyer-m6), which was
//   deliberately rebuilt from 3 shallow lessons into the real 21-lesson
//   flagship course from the recording package -- those are new keys
//   (flyer-1_1 etc), not preserved from the old spark-1_1/design-1_3.
//   Every other lesson still follows the 4-beat formula: one idea →
//   example → action step → bridge.
// ============================================================
window.FUSE_COURSE = {
"pillars": [

{ "key": "orient", "name": "Orientation", "sub": "Start here — 20 minutes, then you create", "tier": "starter", "modules": [
{ "key": "orient-m1", "title": "Start Here", "lessons": [
{ "key": "orient-0_1", "n": "0.1", "title": "Welcome — What You Just Unlocked", "dur": "2 min",
"notes": "<span class='vault-tag'>🎙 Welcome</span><h4>The Idea</h4><p>Fuse Atelier is three things in one: the course (6 skill families), the studio (where you create), and the Money Engine (how you get paid). Your tier unlocks your families — and every tier includes the Money Engine.</p><div class='vault-action'><b>Action step:</b> Open the Create tab and look around for 2 minutes. Next: the one rule that makes this course work.</div>" },
{ "key": "orient-0_2", "n": "0.2", "title": "The Rule: One Skill → Money → Stack The Next", "dur": "1 min",
"notes": "<span class='vault-tag'>🎙 Welcome</span><h4>The Idea</h4><p>People fail courses by learning everything and selling nothing. Here you learn ONE skill in short, focused lessons, monetize it the same week with the Money Engine, then stack the next skill. Momentum beats knowledge.</p><div class='vault-action'><b>Action step:</b> Say your commitment out loud: one skill, one week, one client. Next: your quick self-audit.</div>" },
{ "key": "orient-0_3", "n": "0.3", "title": "Your Starter Audit", "dur": "2 min",
"notes": "<span class='vault-tag'>🎙 Welcome</span><h4>The Idea</h4><p>Rate yourself 1–5 on: AI tools, design eye, selling confidence, and consistency. No wrong answers — this tells you which lessons to slow down on. You'll re-rate at day 30 and shock yourself.</p><div class='vault-action'><b>Action step:</b> Write your 4 ratings somewhere you'll find them again. Next: meet the studio.</div>" },
{ "key": "orient-0_4", "n": "0.4", "title": "Meet Your Studio (Make Your First Image Now)", "dur": "4 min",
"notes": "<span class='vault-tag'>🖥 Screen</span><h4>The Idea</h4><p>A 3-minute tour of Fuse Studio — Image, Video, Avatar, Reactor — ending with YOU generating your first image. The tool is included in your tier; your credits are already loaded.</p><div class='vault-action'><b>Action step:</b> Generate one image of anything. Post it in the community. You're officially a creator. Next: pick your first money skill.</div>" },
{ "key": "orient-0_5", "n": "0.5", "title": "Pick Your First Skill (60-Second Quiz)", "dur": "3 min",
"notes": "<span class='vault-tag'>🎙 Welcome</span><h4>The Idea</h4><p>Fastest money for most people: flyers (every business needs them). Have product-seller friends? Start with product photography. Love video? AI UGC. Pick with your gut — you'll stack the others later anyway.</p><div class='vault-action'><b>Action step:</b> Open your chosen family and start lesson 1 TODAY, not tomorrow. The WhatsApp coach will hold you to it.</div>" }
]}
]},

{ "key": "design", "name": "DESIGN & FLYERS", "sub": "The fastest money — every business buys these", "tier": "starter",
"resources": [
{ "title": "50 Flyer Prompt Directions", "desc": "Every niche, hero-image prompt and typography direction, ready to paste into Flyer Studio.", "url": "/app/media/resources/50-Flyer-Prompt-Directions.pdf" }
],
"modules": [
{ "key": "flyer-m1", "title": "Module 1 · The Foundations Nobody Skips", "lessons": [
{ "key": "flyer-1_1", "n": "1.1", "title": "The Four Rules That Make Anything Look Designed",
"notes": "<span class='vault-tag'>🎙 Avatar</span><h4>The Full Script</h4><p>Every flyer that looks \"off\" — even when you can't say exactly why — is breaking one of four rules. Learn these four, and you'll be able to look at any design, yours or someone else's, and know exactly what's wrong with it. This comes from one of the most widely taught frameworks in graphic design, and it's called C-R-A-P. Yes, really.</p><p><b class='vault-hl'>Contrast</b>. If two things aren't the same, <b class='vault-hl'>make them very different</b> — not just a little different. A headline that's only slightly bigger than the subhead reads as a mistake, not a choice.</p><p><b class='vault-hl'>Repetition</b>. <b class='vault-hl'>Repeat a color, a shape, a font weight</b> across your design, so it reads as one system, not a pile of separate decisions.</p><p><b class='vault-hl'>Alignment</b>. Nothing gets placed randomly. Every single element should <b class='vault-hl'>line up with something else</b> — an edge, a center line, another element.</p><p>And <b class='vault-hl'>Proximity</b>. <b class='vault-hl'>Related things sit close together</b>. Unrelated things get real space between them. Grouping does the organizing for you — you don't need a line to separate two things if the space between them already does the job.</p><p>Here's your homework for this lesson: find one flyer online that looks a bit off to you, and figure out which one of these four rules it's breaking. That habit — turning \"something feels wrong\" into \"the contrast is too weak\" — is worth more than anything else I'll teach you this week.</p><div class='vault-action'><b>Action step:</b> Find one flyer online that looks a bit off and name which of the four rules it's breaking.</div>" },
{ "key": "flyer-1_2", "n": "1.2", "title": "Color That Doesn't Fight Itself",
"notes": "<span class='vault-tag'>🎙 Avatar</span><h4>The Full Script</h4><p>Let's talk about color, because this is where most beginner flyers go wrong first. Here's the one rule that fixes almost all of it: <b class='vault-hl'>pick exactly one saturated accent color</b>. Just one. That color shows up in your headline accent, your badge, your bullet markers, your call to action — everywhere. <b class='vault-hl'>Everything else in the flyer stays dark, neutral, or toned down</b>.</p><p>That single decision is what separates a flyer that looks calm and premium from one that looks like a rainbow exploded.</p><p>Quickly, on the color wheel — complementary colors sit opposite each other and create high energy, so use them sparingly. Analogous colors sit next to each other and feel calm and cohesive. And triadic colors are evenly spaced around the wheel — vibrant, but harder to balance, so be careful with those as a beginner.</p><p>And one more thing — legibility. If you're putting white text over a photo, <b class='vault-hl'>that photo needs a genuinely dark area behind the text</b>, not just \"not white.\" That's exactly why we have tools like drop shadows and glass panels in Fuse Studio — they exist to solve this exact problem, not just to look nice.</p><div class='vault-action'><b>Action step:</b> Pick your one accent color for your next flyer before you open the studio, not after.</div>" },
{ "key": "flyer-1_3", "n": "1.3", "title": "Typography That Doesn't Look Homemade",
"notes": "<span class='vault-tag'>🎙 Avatar</span><h4>The Full Script</h4><p>Typography is where a flyer either whispers \"professional\" or shouts \"I made this in five minutes on my phone.\" Here's how to make sure it's the first one.</p><p>Rule one — <b class='vault-hl'>never use more than two, maybe three fonts</b> in one flyer. One bold, heavy font for your headline. One clean, easy-to-read font for your body text. And if you want a third, maybe a script or a mono font, just for a small accent. More than that, and it reads as indecision, not style.</p><p>Rule two — <b class='vault-hl'>pair fonts by contrast, not similarity</b>. Two similar-looking sans-serif fonts at the same weight will actually fight each other. But a heavy, bold headline font paired with a light, open body font? That looks intentional immediately.</p><p>And rule three — <b class='vault-hl'>build hierarchy using size, weight, AND color, in that order</b>. Someone should be able to glance at your flyer for two seconds and know exactly what to read first, second, and third — even from a blurry thumbnail on their phone.</p><div class='vault-action'><b>Action step:</b> Audit your last flyer — count the fonts. More than three? Cut it down.</div>" },
{ "key": "flyer-1_4", "n": "1.4", "title": "Composition and Layout",
"notes": "<span class='vault-tag'>🎙 Avatar</span><h4>The Full Script</h4><p>Last foundational lesson before we get into the anatomy of an actual flyer — composition.</p><p>First: <b class='vault-hl'>the rule of thirds</b>. Imagine your flyer divided into a three-by-three grid. Your focal point — your hero image, your headline — should sit along those grid lines, not dead center. Dead-centering everything is one of the fastest ways a design reads as amateur, so resist that urge.</p><p>Second: <b class='vault-hl'>one focal point, period</b>. One core message, one hero visual. The moment you have two things competing for attention, you've lost your reader before they even start.</p><p>And third — <b class='vault-hl'>whitespace is not empty space</b>. It's what makes your one focal point actually feel important. If a client tells you \"it needs more,\" your job is to explain why less is doing more work here, not to just cram the page full to make them feel like they got their money's worth.</p><div class='vault-action'><b>Action step:</b> Re-crop one old flyer so the hero sits on a third instead of dead center and compare.</div>" }
]},
{ "key": "flyer-m2", "title": "Module 2 · The Anatomy of a Flyer That Actually Converts", "lessons": [
{ "key": "flyer-2_1", "n": "2.1", "title": "The 7 Layers of a Working Flyer",
"notes": "<span class='vault-tag'>🎙 Avatar</span><h4>The Full Script</h4><p>This is the framework I actually use myself, every time, and it's the single most useful thing in this entire module. Every flyer that really works has these seven layers.</p><p>One — <b class='vault-hl'>the field</b>, your background. Never flat plain white. A gradient, a saturated flat color, or a quiet texture, kept subtle enough that it never competes with your headline.</p><p>Two — <b class='vault-hl'>the hero</b>. One dominant subject, lit with one clear light source. A person, chest-up, confident. Or a product, with one dramatic prop doing the emotional work.</p><p>Three — <b class='vault-hl'>one accent color</b> that pops, reused everywhere — headline, badge, bullets, call to action.</p><p>Four — <b class='vault-hl'>the headline zone</b>. Protected space, upper third to mid-frame, heavy bold type, one word breaking into your accent color.</p><p>Five — <b class='vault-hl'>the information card</b>. Your bullets or pricing, inside one rounded panel, beside or below the hero, never over it.</p><p>Six — a <b class='vault-hl'>signature micro-motif</b>. One or two small recurring details — a sparkle, a badge shape, an underline swipe — repeating two to four times.</p><p>And seven — <b class='vault-hl'>the contact footer</b>. A fixed strip at the bottom, visually separated, holding your contact details.</p><p>Learn these seven layers, and you'll never look at a blank flyer and wonder where to start again.</p><div class='vault-action'><b>Action step:</b> Take your next flyer and label which of the 7 layers each element belongs to — if something doesn't fit a layer, question why it's there.</div>" },
{ "key": "flyer-2_2", "n": "2.2", "title": "Flyer Types and Their Real Conventions",
"notes": "<span class='vault-tag'>🎙 Avatar</span><h4>The Full Script</h4><p>Not every flyer follows the same rules, because not every flyer is selling the same thing. Let's go through the main types.</p><p>Event flyers — parties, launches, conferences. <b class='vault-hl'>The date, time, and venue have to be readable at a glance</b> on a phone screen. Mood and energy matter more than information density here.</p><p>Promo and sale flyers — <b class='vault-hl'>the offer itself, your price or your discount, IS the headline</b>. It's not an afterthought buried in small text. Urgency goes in a badge or a callout box, front and center.</p><p>Business and service flyers — <b class='vault-hl'>credibility matters more than flash</b> here. A badge, a guarantee line, a real photo. And the call to action needs to be one single, obvious next step, not three options.</p><p>And personal brand or portfolio flyers — <b class='vault-hl'>the person's face and name carry the whole hierarchy</b>. Everything else supports, nothing competes.</p><div class='vault-action'><b>Action step:</b> Identify which of the 4 types your next 3 client jobs are, before you design a single one.</div>" },
{ "key": "flyer-2_3", "n": "2.3", "title": "Sizing and Platforms",
"notes": "<span class='vault-tag'>🎙 Avatar</span><h4>The Full Script</h4><p>Quick but important lesson — where is this flyer actually going to live?</p><p>One-to-one and four-to-five are your Instagram and Facebook feed sizes — <b class='vault-hl'>four-to-five generally gets more engagement</b> because it takes up more of the scroll.</p><p>Nine-to-sixteen is for Stories, Reels covers, and WhatsApp Status — <b class='vault-hl'>keep your text clear of the very top and bottom</b>, since that's where the platform's own buttons usually sit.</p><p>Three-to-four is a nice middle ground when four-to-five feels a bit too tall for what you're designing.</p><p>And if a client ever wants something printed — know that print sizes need extra edge space called <b class='vault-hl'>bleed</b>, which gets trimmed off after printing. You don't need to be a print expert, but knowing this one term will save you from a very confused conversation with a client one day.</p><div class='vault-action'><b>Action step:</b> Before your next job, confirm every size the client actually needs — don't assume it's just one.</div>" },
{ "key": "flyer-2_4", "n": "2.4", "title": "The Mistakes That Scream \"Beginner\"",
"notes": "<span class='vault-tag'>🎙 Avatar</span><h4>The Full Script</h4><p>Let's end this module with a checklist — the mistakes that instantly tell a client \"this person is new at this.\"</p><p>One — <b class='vault-hl'>a wall of text with no hierarchy</b>. If everything is the same size, nothing feels important.</p><p>Two — <b class='vault-hl'>white text placed directly on a busy photo with nothing behind it</b>. No shadow, no glow, no panel. This is the single most common legibility mistake I see, and it's the easiest one to fix.</p><p>Three — <b class='vault-hl'>more than three fonts</b>, or fonts too similar to read as an intentional pairing.</p><p>Four — <b class='vault-hl'>no single focal point</b>. The eye doesn't know where to land first.</p><p>Five — <b class='vault-hl'>generic stock-photo energy</b>. A random smiling model with zero connection to the actual brand.</p><p>And six — <b class='vault-hl'>more than one color trying to \"pop\" at once</b>.</p><p>Run every flyer you make through this list before you send it to a client. It takes thirty seconds and it will save you from ever delivering something that looks unfinished.</p><div class='vault-action'><b>Action step:</b> Run your last 3 delivered flyers through this checklist. Fix whatever fails before your next delivery.</div>" }
]},
{ "key": "flyer-m3", "title": "Module 3 · Designing with AI (Fuse Studio Workflow)", "lessons": [
{ "key": "flyer-3_1", "n": "3.1", "title": "Research First: Building Your Reference Board",
"notes": "<span class='vault-tag'>🖥 Screen</span><h4>What This Lesson Covers</h4><p>Before you ever open Fuse Studio for a real flyer, there's a research step that decides more about the final quality than anything you'll do inside the tool. <b class='vault-hl'>You need your own creative direction before you ask AI for anything</b> — if you just say \"design this for me\" with no direction, you get something generic back.</p><p>The method: open <b class='vault-hl'>Pinterest</b> and search for the exact thing you're designing — the product name, an event type, whatever matches your brief. You're not looking for one perfect image. You're gathering three separate categories of reference:</p><p><b class='vault-hl'>The hero visual</b> — how you want the actual product or subject rendered (the surface it's sitting on, the render style, the mood).</p><p><b class='vault-hl'>The background structure</b> — the setting, color, and texture behind your hero.</p><p><b class='vault-hl'>The headline style</b> — how the typography and layout should feel, kept separate from any one flyer's exact wording so you're not just copying someone's design.</p><p>Keep searching until each of the three feels right — <b class='vault-hl'>this step takes longer than anything else in the whole process</b>, and that's normal. Save every reference you land on; you'll upload these directly into Fuse Studio in the next lesson.</p><div class='vault-action'><b>Action step:</b> Before your next flyer, save at least 3 references each for hero, background, and headline style — don't open Fuse Studio until you have all three.</div>" },
{ "key": "flyer-3_2", "n": "3.2", "title": "Uploading References & Writing the Brief",
"notes": "<span class='vault-tag'>🖥 Screen</span><h4>What This Lesson Covers</h4><p>Now you take everything you saved from your Pinterest research and bring it into Flyer Studio. Open <b class='vault-hl'>Add References</b> and upload your actual product photo first — that's your real subject, not a mood reference.</p><p>Then upload your saved references and <b class='vault-hl'>tag each one by exactly what it's there for</b> — hero structure, headline structure, features, background — and remove any reference slot you're not actually using so it doesn't confuse the generation.</p><p>Next, describe what you want in the brief: <b class='vault-hl'>aspect ratio, the product, the color direction, and the format</b> (e.g. a product showcase). Fuse Studio's assistant responds with a full breakdown — purpose and audience, the color palette, and the composition, including exactly which of your tagged references it's pulling each decision from.</p><p><b class='vault-hl'>Read through everything it gives you before moving on</b> — if something's off (a color that doesn't match what you want, a background it misread), correct it in your next message rather than approving blindly. Once it's right, it writes the actual generation prompt for you.</p><div class='vault-action'><b>Action step:</b> Upload one real brief's references, tag every one correctly, and read the assistant's full response before approving — don't just skim and hit generate.</div>" },
{ "key": "flyer-3_3", "n": "3.3", "title": "Hero, Add a Layer & Composite — Building the Final Flyer",
"notes": "<span class='vault-tag'>🖥 Screen</span><h4>What This Lesson Covers</h4><p>Once you have a hero result, refine it. If it's close but not exact, go back to your references and <b class='vault-hl'>turn off any tags you don't need for this specific regeneration</b> — e.g. keep only hero structure and background on, headline and features off — and let it try again focused on just those two.</p><p>Once the hero looks right, move to <b class='vault-hl'>Add a Layer</b>. Upload your generated hero image, then describe exactly what you want added — a texture, extra lighting, an effect on the background. The tool will also <b class='vault-hl'>look at your image and suggest things you could add</b> — read its suggestions, but don't feel like you have to take all of them; use what actually fits your direction.</p><p>Then move into <b class='vault-hl'>Typography</b>: tag your headline structure and feature-placement references, edit the actual headline and sub-heading text, and choose your text panel style (gradient, drop shadow). <b class='vault-hl'>Accent color auto-selects to match your product</b> — you generally don't need to touch it.</p><p>Hit Composite. <b class='vault-hl'>Expect to regenerate two to three times</b> before it matches what's in your head — the first result is rarely the final one, and that's completely normal, not a sign something's wrong.</p><div class='vault-action'><b>Action step:</b> Run one flyer through the full pipeline — hero refine, Add a Layer, Typography, Composite — and regenerate at least once instead of settling for the first result.</div>" },
{ "key": "flyer-3_4", "n": "3.4", "title": "The Final Polish — Lightroom Color Grade & Client-Ready Export",
"notes": "<span class='vault-tag'>🖥 Screen</span><h4>What This Lesson Covers</h4><p>Your Composite result out of Fuse Studio is already good — this last pass is what pushes it from good to <b class='vault-hl'>premium</b>. Export your finished flyer and open it in Lightroom Mobile (free). <b class='vault-hl'>Don't add too much effect</b> — every setting here is a light touch, not a redo.</p><p>In the <b class='vault-hl'>Effects panel</b>: Texture around 50 (this is what gives your design that subtle premium grain-and-depth look). Clarity — keep it very low, no higher than 5. Dehaze — same, no higher than 5, it adds saturation fast if you push it. Vignette — skip it unless you specifically want a center-of-attention pull. A touch of Grain is what makes the final image read as intentional and modern rather than flat.</p><p>In <b class='vault-hl'>Detail</b>: sharpen slightly, and reduce noise slightly — both light-touch, not maxed out.</p><p>Pick a <b class='vault-hl'>Profile</b> that pulls your colors closer together — try a few and pick whichever matches the palette you're going for (there's usually one built around pinks/warms that suits product flyers particularly well).</p><p>Then <b class='vault-hl'>Color Grading</b>: nudge the midtones toward your flyer's accent color, then use the Balance slider to blend it back in — push too far and pull it back rather than committing to the first result.</p><p>Compare your before and after side by side. <b class='vault-hl'>That visible difference is what makes a client think \"this person actually knows what they're doing.\"</b></p><p>Finally — <b class='vault-hl'>if your client wants a printable file</b>, don't just hand over the PNG. Run it through any free \"Image to PDF\" app (Play Store, or Chrome's own print-to-PDF) so what you deliver looks like a finished, print-ready document, not a random image file.</p><div class='vault-action'><b>Action step:</b> Take one flyer you already composited in Fuse Studio and run it through this exact Lightroom pass — texture, clarity, dehaze, grain, sharpen, profile, color grading — then compare before/after and export a PDF version.</div>" },
]},
{ "key": "flyer-m4", "title": "Module 4 · Research Like a Real Designer, for Any Niche", "lessons": [
{ "key": "flyer-4_1", "n": "4.1", "title": "The Method",
"notes": "<span class='vault-tag'>🎙 Avatar</span><h4>The Full Script</h4><p>Here's the habit that separates a designer clients trust with brand-new industries from one who only ever makes the same generic-looking thing. Four steps, and you can apply this to literally any niche a client hands you.</p><p>Step one — <b class='vault-hl'>find two to four real, well-regarded brands or creators</b> actually working in this niche right now. Not generic stock-image ideas of the industry. Actual current players.</p><p>Step two — ask yourself <b class='vault-hl'>what's the lazy, obvious default</b> everyone assumes for this niche, and <b class='vault-hl'>what do the genuinely respected players do instead</b>? That gap, right there, is where \"looks premium\" actually lives.</p><p>Step three — <b class='vault-hl'>pin down exactly one real color anchor, one named typography mood, and one motif system</b> tied to that niche's actual culture. Not vague ideas. Specific choices.</p><p>And step four — <b class='vault-hl'>restraint beats maximalism, always</b>. One or two colors. One or two typefaces. Authenticity is usually one very specific choice, not more of everything associated with the category.</p><p>Do this BEFORE you open Fuse Studio, every single time, for every new niche. It's four extra minutes of thinking that changes the entire quality of what you deliver.</p><div class='vault-action'><b>Action step:</b> Run all 4 steps on paper for the very next niche a client hands you, before opening Fuse Studio.</div>" },
{ "key": "flyer-4_2", "n": "4.2", "title": "Worked Example: Web3/Crypto",
"notes": "<span class='vault-tag'>🖥 Screen</span><h4>What This Lesson Covers</h4><p>A full live walkthrough — building a real Web3/DAO governance flyer called <b class='vault-hl'>Nexroot</b>, start to finish, inside Flyer Studio's actual chat.</p><p><b class='vault-hl'>Reference research first</b> — two real Web3 flyers gathered using the research method from 4.1, each tagged with exactly what to take: one purely for its bold gradient headline treatment, its small pill badge, and its QR-code corner placement — never its actual words, icons, or hero figure. The other purely for the hero-visual staging: the glossy orb-with-orbiting-icons composition and 3D lighting.</p><p><b class='vault-hl'>Let the chat write the brief</b> — attach your tagged references, describe the concept in plain English, and the assistant writes back the full numbered reference mapping plus a proposed composition, palette, and background — read through it before you say yes to generate.</p><p><b class='vault-hl'>Hero result not loading?</b> — download it and re-upload it yourself as the working hero rather than sitting there waiting on a slow connection to register it.</p><p><b class='vault-hl'>Suggest Layers reads your own image</b> — it proposes real lighting/texture add-ons based on what's already in your hero. Only add what genuinely fits; it's fine to add nothing.</p><p><b class='vault-hl'>Typography panel</b> — headline, accent word, subhead, bullets, badge, and footer all come pre-filled from the brief, accent color auto-matched to your palette. Attach your headline/feature/CTA structure references here too, before compositing.</p><p><b class='vault-hl'>Fix a Spot beats a full regenerate</b> — when one specific element isn't right (in this lesson, a set of icons), circle just that part and say exactly what to clear or change instead of starting the whole flyer over.</p><div class='vault-action'><b>Action step:</b> Build one real flyer this exact way, start to finish — references tagged, brief written, hero generated, a layer considered, typography composited, one spot fixed. Then grab the 50-prompt resource pack below Module 6 for your next one.</div>" },
{ "key": "flyer-4_3", "n": "4.3", "title": "Building This Instinct For Every New Niche",
"notes": "<span class='vault-tag'>🎙 Avatar</span><h4>The Full Script</h4><p>Your assignment for this module — and I mean actually do this, don't just watch — pick three niches you know nothing about. Maybe a local fashion boutique, a fintech app, and a fitness coach. For each one, <b class='vault-hl'>run the four-step method from lesson one, on paper or in your notes app, BEFORE you touch Fuse Studio at all</b>.</p><p>Write down your two to four real reference brands. Write down the lazy default and what the real players do instead. Pin your one color, one typography mood, one motif.</p><p>Only after you've done that for all three, go generate a flyer for each one. You'll notice something — <b class='vault-hl'>the flyers won't look like each other, and they won't look generic</b>. That's the whole point. This is the difference between a designer who can only do one style, and one who clients trust to walk into any industry.</p><div class='vault-action'><b>Action step:</b> Do the 3-niche exercise for real. Don't skip to generating — the research step is the actual skill being taught.</div>" }
]},
{ "key": "flyer-m5", "title": "Module 5 · From Brief to Paid Delivery", "lessons": [
{ "key": "flyer-5_1", "n": "5.1", "title": "Running the Real Client Conversation",
"notes": "<span class='vault-tag'>🎙 Avatar</span><h4>The Full Script</h4><p>All the design skill in the world means nothing if you can't actually run a client conversation. Here's exactly what to ask, every time, before you generate a single thing.</p><p><b class='vault-hl'>What is this actually for</b>. <b class='vault-hl'>Who's the audience</b>. <b class='vault-hl'>Is there an existing brand or color palette to match</b>. <b class='vault-hl'>What's the one thing this flyer absolutely needs to communicate</b>. And <b class='vault-hl'>are there any reference images</b> — a product shot, a competitor flyer, anything they like the look of.</p><p>And here's the part most beginners get wrong — when a client is vague, and they often will be, don't just sit there waiting for more information. <b class='vault-hl'>Fill the gaps yourself, using everything you learned in this course, and show them a complete direction to react to</b>. Clients are much better at saying \"change this\" than they are at describing what they want from nothing. Give them something real to respond to, always.</p><div class='vault-action'><b>Action step:</b> Write these 5 questions into a saved WhatsApp quick-reply for your next client intake.</div>" },
{ "key": "flyer-5_2", "n": "5.2", "title": "Revisions Without Scope Creep",
"notes": "<span class='vault-tag'>🎙 Avatar</span><h4>The Full Script</h4><p>Quick, important lesson on protecting your time and your pricing. Before you even start a job, <b class='vault-hl'>agree on the number of revision rounds</b>. Two rounds is completely standard for a simple flyer — say that upfront, every time.</p><p>And here's the definition that keeps this from getting messy — <b class='vault-hl'>a revision is a change to the brief you already agreed on</b>. A brand new direction after you've already delivered an approved design is a new job, not a revision. You're allowed to say that, kindly but clearly. \"<b class='vault-hl'>Happy to explore that — since it's a new direction, let's scope it as a separate small job.</b>\" That one sentence will save you from working for free more times than you'd expect.</p><div class='vault-action'><b>Action step:</b> Save that exact sentence into your phone's quick replies.</div>" },
{ "key": "flyer-5_3", "n": "5.3", "title": "Delivery",
"notes": "<span class='vault-tag'>🎙 Avatar</span><h4>The Full Script</h4><p>Delivery is simple, but small mistakes here make you look unprofessional even when the design itself was great.</p><p><b class='vault-hl'>Always deliver the exact sizes the brief actually called for</b> — if they need a feed post, a story, and a status update, deliver all three from the SAME visual, not three unrelated designs that don't match.</p><p>On file formats — <b class='vault-hl'>PNG whenever transparency matters or when text sharpness is the priority</b>. JPEG is fine for a final, flat flyer where file size matters more, like something going straight to WhatsApp.</p><p>That's genuinely it. <b class='vault-hl'>Get the sizes right, get the format right, and deliver on time</b> — that alone puts you ahead of a lot of people doing this.</p><div class='vault-action'><b>Action step:</b> Build yourself a delivery checklist (sizes, formats, filenames) and use it on every job from now on.</div>" },
{ "key": "flyer-5_4", "n": "5.4", "title": "Every Job Is a Portfolio Piece",
"notes": "<span class='vault-tag'>🎙 Avatar</span><h4>The Full Script</h4><p>Last lesson in this module, and it's the one that compounds the most over time. <b class='vault-hl'>Save the brief and the final result together, for every single job you do</b> — even the small ₦10,000 ones, even the ones you're not that proud of.</p><p>Here's why this matters so much — <b class='vault-hl'>a portfolio piece that shows a real brief next to a real result reads as proof you can actually interpret direction</b>. A portfolio that's just a gallery of pretty images proves nothing except that you can make pretty images. Clients hiring you are betting on whether you can take THEIR vague idea and turn it into something real — showing them you've done that before, with an actual brief attached, is worth more than twenty extra samples with no context.</p><div class='vault-action'><b>Action step:</b> Go back and pair up briefs with results for your existing portfolio pieces, starting today.</div>" }
]},
{ "key": "flyer-m6", "title": "Module 6 · Practice Curriculum", "lessons": [
{ "key": "flyer-6_1", "n": "6", "title": "Your 5 Practice Briefs",
"notes": "<span class='vault-tag'>🎙 Avatar</span><h4>The Full Script</h4><p>Here's your practice curriculum — five briefs, in order, each one increasing in difficulty and forcing a specific skill from everything we've covered.</p><p><b class='vault-hl'>Brief one</b> — a simple promo flyer, no reference images at all. This forces you to use everything from the foundations module with nothing to lean on.</p><p><b class='vault-hl'>Brief two</b> — a product flyer, using one real product reference photo. This forces you to use edit mode correctly and keep that product looking exactly like itself.</p><p><b class='vault-hl'>Brief three</b> — an event flyer, but in a niche you know nothing about. This forces you to actually run the research method before you generate anything.</p><p><b class='vault-hl'>Brief four</b> — clone the structure of a real flyer you find online, but with completely new copy and a different product. This proves you understand the difference between copying a layout and copying content.</p><p>And <b class='vault-hl'>brief five</b> — a real, or simulated, client brief, delivered in all three platform sizes, with a two-round revision cycle. This forces the entire workflow, start to finish, exactly like a real paid job.</p><p><b class='vault-hl'>Do these five, in order, don't skip ahead</b>. By the end, you won't just have watched a course — you'll have five real pieces in your portfolio, and the actual muscle memory to do this for a paying client tomorrow.</p><div class='vault-action'><b>Action step:</b> Do all 5, in order, don't skip ahead — by the end you'll have 5 real portfolio pieces and the muscle memory for a real paying job.</div>" }
]}
]},

{ "key": "brand", "name": "BRAND IDENTITY", "sub": "Premium packages — logos, kits and voice", "tier": "creator", "modules": [
{ "key": "brand-m1", "title": "Skill 4 · Logo & Brand Kits", "lessons": [
{ "key": "brand-1_1", "n": "4.1", "title": "Learn It: What A ₦50k Brand Kit Contains", "dur": "6 min",
"notes": "<span class='vault-tag'>🎙 Voice</span><h4>The Idea</h4><p>Clients don't buy 'a logo' — they buy looking legit: logo + colours + fonts + brand board, packaged. Sell the kit, not the file. The packaging is why one designer charges ₦70k while another begs at ₦5k.</p><div class='vault-action'><b>Action step:</b> Collect 3 brand kits you admire (search 'brand board'). Next: generating logo directions in minutes.</div>" },
{ "key": "brand-1_2", "n": "4.2", "title": "Build It: Logo Directions & The Full Kit", "dur": "9 min",
"notes": "<span class='vault-tag'>🖥 Screen</span><h4>The Idea</h4><p>Generate 3 distinct logo directions (wordmark, icon, badge), refine the winner, extract the palette, pair two fonts, and assemble the brand board — all inside the studio in one sitting.</p><div class='vault-action'><b>Action step:</b> Build one complete kit for a fictional brand. Next: the presentation that makes it worth ₦50k.</div>" },
{ "key": "brand-1_3", "n": "4.3", "title": "Sell It: Present Like An Agency, Charge Like One", "dur": "6 min",
"notes": "<span class='vault-tag'>🎙 Voice</span><h4>The Idea</h4><p>Present 2 directions max, on mockups (signage, business card, IG grid), with one paragraph of strategy each. Price tiers: kit ₦25k · kit + stationery ₦45k · kit + stationery + content starter pack ₦70k.</p><div class='vault-action'><b>Action step:</b> Put your fictional kit on 3 mockups. That's portfolio piece #1 for the Brand family.</div>" }
]},
{ "key": "brand-m2", "title": "Skill 5 · Brand Stationery", "lessons": [
{ "key": "brand-2_1", "n": "5.1", "title": "Learn & Build: Cards, Letterheads & Signatures", "dur": "8 min",
"notes": "<span class='vault-tag'>🖥 Screen</span><h4>The Idea</h4><p>Stationery is the easiest upsell in design: business cards, letterheads, email signatures — generated from the brand kit's colours and fonts so everything matches. 30 minutes of work, ₦5k–20k added to every brand job.</p><div class='vault-action'><b>Action step:</b> Extend your fictional brand kit with a card + letterhead. Next: the words that complete a brand.</div>" },
{ "key": "brand-2_2", "n": "5.2", "title": "Sell It: The Automatic Upsell Script", "dur": "4 min",
"notes": "<span class='vault-tag'>🎙 Voice</span><h4>The Idea</h4><p>After every logo/kit delivery: 'Want me to extend this to your cards, letterhead and email signature so everything matches? ₦X if we do it this week.' Asked at the moment of delight, this closes half the time.</p><div class='vault-action'><b>Action step:</b> Save the upsell script into your phone's quick replies. It will pay you for years.</div>" }
]},
{ "key": "brand-m3", "title": "Skill 6 · Brand Voice & Captions", "lessons": [
{ "key": "brand-3_1", "n": "6.1", "title": "Learn & Build: Bios, Taglines & 30-Day Calendars", "dur": "8 min",
"notes": "<span class='vault-tag'>🖥 Screen</span><h4>The Idea</h4><p>Fuse Reactor writes what the brand sounds like: bio, tagline, tone rules, and a 30-day content calendar. Words are the invisible half of branding — and almost nobody in your market sells them properly.</p><div class='vault-action'><b>Action step:</b> Generate a voice pack for your fictional brand. Next: bundling words + visuals into one premium offer.</div>" },
{ "key": "brand-3_2", "n": "6.2", "title": "Sell It: The Complete Brand Package", "dur": "5 min",
"notes": "<span class='vault-tag'>🎙 Voice</span><h4>The Idea</h4><p>Kit + stationery + voice + content starter = 'everything a new business needs to launch, in one week' — ₦70k–150k depending on the client. You are no longer a designer; you're a launch partner.</p><div class='vault-action'><b>Action step:</b> Write your complete-package offer as one page. New businesses register every day — the Money Engine shows you where they announce themselves.</div>" }
]}
]},

{ "key": "product", "name": "PRODUCT & E-COMMERCE", "sub": "Sellers pay for photos that sell things", "tier": "creator", "modules": [
{ "key": "product-m1", "title": "Skill 7 · AI Product Photography", "lessons": [
{ "key": "spark-2_1", "n": "7.1", "title": "Learn It: What Clients Actually Pay For", "dur": "2 min",
"notes": "<span class='vault-tag'>🎙 Voice</span><h4>The Idea</h4><p>Brands need shots for their website, IG grid, ads and packaging — studio photography costs hundreds of dollars per shot. You deliver the same from one phone photo, in minutes, and still charge well.</p><div class='vault-action'><b>Action step:</b> Take one plain reference photo of any product near you. Next: turning it into a studio shot.</div>" },
{ "key": "spark-2_2", "n": "7.2", "title": "Build It: Surfaces, Environments & Brand Colours", "dur": "9 min",
"notes": "<span class='vault-tag'>🖥 Screen</span><h4>The Idea</h4><p>Upload the reference photo, then prompt the world around it: marble counter with soft morning light, or a bold colour-matched backdrop. The product stays accurate because it's grounded in a real image. Match backdrops to the client's brand colour — consistency beats prettiness.</p><div class='vault-action'><b>Action step:</b> Generate 3 context variations of your product: luxury, bold brand-colour, outdoor lifestyle. Next: premium finishes and delivery.</div>" },
{ "key": "spark-2_3", "n": "7.3", "title": "Sell It: Beauty & Luxury Renders + Client Delivery", "dur": "21 min",
"notes": "<span class='vault-tag'>🖥 Screen</span><h4>The Idea</h4><p>The premium tier: beauty/luxury lighting, water splashes, floating products — plus how to deliver: upscaled, in a named folder, with a one-line usage guide. Charge ₦2k–5k per finished shot, ₦10k–40k per campaign set.</p><div class='vault-action'><b>Action step:</b> Produce a 5-shot set for one product and package it like a delivery. That's your Product-family portfolio piece.</div>" }
]},
{ "key": "product-m2", "title": "Skill 8 · Product Ads & Campaign Shots", "lessons": [
{ "key": "product-2_1", "n": "8.1", "title": "Learn & Build: Lifestyle Scenes & Seasonal Campaigns", "dur": "8 min",
"notes": "<span class='vault-tag'>🖥 Screen</span><h4>The Idea</h4><p>A product photo shows the thing; a campaign shot shows the life around it — the woman wearing the scarf at a rooftop dinner, the drink sweating on a beach table. Seasonal hooks (Detty December, Valentine's, back-to-school) sell campaign SETS, not singles.</p><div class='vault-action'><b>Action step:</b> Take your product from 7.3 and build 3 lifestyle scenes around one season. Next: pricing campaign work.</div>" },
{ "key": "product-2_2", "n": "8.2", "title": "Sell It: Campaign Sets & The Seasonal Calendar", "dur": "5 min",
"notes": "<span class='vault-tag'>🎙 Voice</span><h4>The Idea</h4><p>Pitch 6 weeks before each season: 'Your Valentine's campaign, done this week — 6 shots, ₦25k.' Sellers plan late; you show up early with samples. The seasonal calendar = 6 guaranteed pitch moments a year.</p><div class='vault-action'><b>Action step:</b> Mark the next 3 Nigerian retail seasons in your calendar with a pitch reminder 6 weeks out.</div>" }
]},
{ "key": "product-m3", "title": "Skill 9 · Packaging & Label Design", "lessons": [
{ "key": "product-3_1", "n": "9.1", "title": "Learn & Build: Labels, Boxes & Pouch Mockups", "dur": "9 min",
"notes": "<span class='vault-tag'>🖥 Screen</span><h4>The Idea</h4><p>Small brands going premium need packaging: label design, box/pouch mockups, shelf-ready looks. Generate the design, place it on realistic mockups, and hand them print-ready direction.</p><div class='vault-action'><b>Action step:</b> Design one label and show it on 2 mockups. Next: who buys this and at what price.</div>" },
{ "key": "product-3_2", "n": "9.2", "title": "Sell It: The ₦20k–80k Packaging Package", "dur": "4 min",
"notes": "<span class='vault-tag'>🎙 Voice</span><h4>The Idea</h4><p>Targets: skincare, food brands, supplements moving from nylon to premium. Price label-only ₦20k, full packaging suite ₦50k–80k. Pair with the Brand family for launch-partner money.</p><div class='vault-action'><b>Action step:</b> List 5 small product brands you know personally whose packaging undersells them. That's a pitch list.</div>" }
]},
{ "key": "product-m4", "title": "Skill 10 · CGI Ads", "lessons": [
{ "key": "product-4_1", "n": "10.1", "title": "Learn It: Why 'Impossible' Ads Go Viral", "dur": "5 min",
"notes": "<span class='vault-tag'>🎙 Voice</span><h4>The Idea</h4><p>A giant perfume bottle landing in Lekki traffic stops thumbs. CGI ads are shareable BECAUSE they're impossible — brands pay for the attention, not the video. One viral CGI ad is a client magnet for you too.</p><div class='vault-action'><b>Action step:</b> Watch 3 CGI ads (search 'CGI ad' on TikTok) and note the pattern: real location + impossible product event. Next: making one.</div>" },
{ "key": "product-4_2", "n": "10.2", "title": "Build & Sell It: Your First CGI Ad", "dur": "10 min",
"notes": "<span class='vault-tag'>🖥 Screen</span><h4>The Idea</h4><p>Generate the real-location base shot, prompt the impossible event around the product, animate with a video model, add sound design. Deliver as 9:16. Charge ₦50k–200k — this is spectacle work, price it like spectacle.</p><div class='vault-action'><b>Action step:</b> Make one CGI ad for a brand you love, post it and tag them. This exact move has landed people retainers.</div>" }
]}
]},

{ "key": "video", "name": "VIDEO & MOTION", "sub": "The dollar skills — UGC, avatars and ads", "tier": "creator", "modules": [
{ "key": "video-m1", "title": "Skill 11 · AI UGC Ads", "lessons": [
{ "key": "video-1_1", "n": "11.1", "title": "Learn It: Why Brands Pay $50–150 Per UGC Video", "dur": "5 min",
"notes": "<span class='vault-tag'>🎙 Voice</span><h4>The Idea</h4><p>Brands burn money on ads; authentic-looking testimonial videos convert best; real creators are slow and expensive. AI UGC = you deliver the winning format at scale, without being on camera. This is the most in-demand dollar skill in this course.</p><div class='vault-action'><b>Action step:</b> Watch 3 UGC ads on any brand's IG. Note the structure: hook → problem → product → result. Next: building yours.</div>" },
{ "key": "spark-5_4", "n": "11.2", "title": "Build It: Create Your First AI UGC Video (Full Tutorial)", "dur": "11 min",
"notes": "<span class='vault-tag'>🎙 Talking head — full recorded walkthrough</span><h4>The Idea</h4><p>The complete start-to-finish build: script, AI presenter, generation and polish — one watch-along tutorial.</p><div class='vault-action'><b>Action step:</b> Build your own first UGC clip while you watch. Next: selling it in packs.</div>" },
{ "key": "video-1_3", "n": "11.3", "title": "Sell It: Hook Variations & The 3-Pack Offer", "dur": "6 min",
"notes": "<span class='vault-tag'>🎙 Voice</span><h4>The Idea</h4><p>Performance marketers A/B test hooks — so sell 3 hook variations of ONE ad, not 3 different ads. Offer: 3-pack $99–150 intro, $50+ per extra variation. Deliver in 48h and you'll be rehired monthly.</p><div class='vault-action'><b>Action step:</b> Produce 2 more hooks for your 11.2 video. You now have a sellable UGC 3-pack — the Money Engine's foreign-client playbook shows you who wants it.</div>" }
]},
{ "key": "video-m2", "title": "Skill 12 · Clone Yourself — Hyper-Real Avatar Videos", "lessons": [
{ "key": "spark-3_4", "n": "12.1", "title": "Learn It: Your Consistent AI Face", "dur": "12 min",
"notes": "<span class='vault-tag'>🎙 Talking head — full recorded walkthrough</span><h4>The Idea</h4><p>Build your consistent AI face in Avatar Studio — the model-sheet method that keeps your face locked across every future generation. This is the foundation the hyper-real clone builds on.</p><div class='vault-action'><b>Action step:</b> Build your model sheet while you watch. Next: the realism jump.</div>" },
{ "key": "video-2_2", "n": "12.2", "title": "Build It: The One-Video Clone (So Real It's Scary)", "dur": "10 min",
"notes": "<span class='vault-tag'>🖥 Screen</span><h4>The Idea</h4><p>Upload one clean photo or short clip + an audio track → InfiniteTalk generates a new talking video of YOU, in any scene, saying anything — full posture, expression and identity preserved, up to 10 minutes long. Use it for your own content (no more recording every video), and sell it as a premium service to personal brands who want daily presence without daily filming.</p><p>For work where realism has to be undetectable — a client contract, a big brand — the premium route is HeyGen's Avatar V, the most realistic engine that exists right now (a documented fix for the 'identity drift' that makes AI clones look off over a full video). It costs more, so save it for the jobs where that difference actually matters.</p><h4>Ria's Shortcut</h4><p>Good light and a plain background on your ONE source clip matters more than anything else — that single recording is what every future video is built from, so don't rush it.</p><div class='vault-action'><b>Action step:</b> Record one clean 30–60 second video of yourself talking to camera (good light, clear audio, plain background). That's your clone source for life. Next: monetizing it.</div>" },
{ "key": "video-2_3", "n": "12.3", "title": "Sell It: Content Systems For Faceless CEOs", "dur": "6 min",
"notes": "<span class='vault-tag'>🎙 Voice</span><h4>The Idea</h4><p>Busy founders and creators want daily video presence without recording daily. Sell 'your month of talking videos from one recording' — $100–500/month per client. Two clients = real salary.</p><div class='vault-action'><b>Action step:</b> List 3 personal brands you follow who post inconsistently. They are the pitch list for this skill.</div>" }
]},
{ "key": "video-m3", "title": "Skill 13 · Advert Videos", "lessons": [
{ "key": "video-3_1", "n": "13.1", "title": "Learn & Build: Script → Scenes → Cut", "dur": "9 min",
"notes": "<span class='vault-tag'>🖥 Screen</span><h4>The Idea</h4><p>A full short-form ad: Reactor writes the 20-second script, you generate each 5–8s scene, then stitch with cuts and music in CapCut. Short clips generate more reliably than long takes — always build in pieces.</p><div class='vault-action'><b>Action step:</b> Make one 20-second ad for any local business, start to finish. Next: pricing video work.</div>" },
{ "key": "video-3_2", "n": "13.2", "title": "Sell It: ₦30k–150k Per Ad", "dur": "5 min",
"notes": "<span class='vault-tag'>🎙 Voice</span><h4>The Idea</h4><p>Local businesses pay ₦30k–80k per finished ad; foreign clients $100–300. Sell in campaign bundles (3 ads, 3 formats) and include one revision round — scope creep is the killer, the contract templates protect you.</p><div class='vault-action'><b>Action step:</b> Send your 13.1 ad to that business with the walk-in/DM script. Real pitch, real practice.</div>" }
]},
{ "key": "video-m4", "title": "Skill 14 · Cinematic Brand Films", "lessons": [
{ "key": "video-4_1", "n": "14.1", "title": "Learn & Build: Direct Like A DP", "dur": "10 min",
"notes": "<span class='vault-tag'>🖥 Screen</span><h4>The Idea</h4><p>Premium storytelling: camera language (lens, movement, light), scene continuity, and a 45–60s brand film structure — arrival, world, product, feeling. This is agency-tier work from your phone.</p><div class='vault-action'><b>Action step:</b> Storyboard 6 shots for a brand you love, generate 3 of them. Next: who pays ₦100k+ for this.</div>" },
{ "key": "video-4_2", "n": "14.2", "title": "Sell It: The ₦100k+ Brand Film Pitch", "dur": "5 min",
"notes": "<span class='vault-tag'>🎙 Voice</span><h4>The Idea</h4><p>Targets: hotels, real estate, restaurants, fashion labels — businesses that sell a feeling. Pitch with a 15-second spec teaser of THEIR brand. Price: ₦100k–400k. One film a month changes your life.</p><div class='vault-action'><b>Action step:</b> Make one 15-second spec teaser for a local premium business. That teaser is your Empire-level calling card.</div>" }
]}
]},

{ "key": "web", "name": "WEB & FUNNELS", "sub": "Premium builds — pages, emails and wow-sites", "tier": "empire", "modules": [
{ "key": "web-m1", "title": "Skill 15 · Landing Pages", "lessons": [
{ "key": "web-1_1", "n": "15.1", "title": "Learn & Build: The One-Day Business Page", "dur": "10 min",
"notes": "<span class='vault-tag'>🖥 Screen</span><h4>The Idea</h4><p>The DemoForge method: hero, services, proof, contact — built and deployed in a day with AI doing the heavy lifting. The secret to selling them: build the demo BEFORE the pitch and send the live link.</p><div class='vault-action'><b>Action step:</b> Build one demo page for a real local business. Next: the pitch that converts demos into deposits.</div>" },
{ "key": "web-1_2", "n": "15.2", "title": "Sell It: ₦50k–250k Per Site", "dur": "6 min",
"notes": "<span class='vault-tag'>🎙 Voice</span><h4>The Idea</h4><p>'I already built your new site — want it?' beats every cold pitch ever written. Price: one-pager ₦50k–100k, multi-section ₦150k–250k, hosting/care ₦5k–10k monthly (recurring!).</p><div class='vault-action'><b>Action step:</b> Send your demo to the business with the pitch script. This exact method has landed real contracts.</div>" }
]},
{ "key": "web-m2", "title": "Skill 16 · Email Design & Sequences", "lessons": [
{ "key": "web-2_1", "n": "16.1", "title": "Learn & Build: Welcome & Sales Sequences", "dur": "9 min",
"notes": "<span class='vault-tag'>🖥 Screen</span><h4>The Idea</h4><p>Businesses with audiences need emails: the 5-email welcome sequence and the sales sequence. Reactor drafts, you polish with brand voice, design clean layouts. Monthly retainer work by nature.</p><div class='vault-action'><b>Action step:</b> Write a 3-email welcome sequence for your fictional brand. Next: packaging email as a service.</div>" },
{ "key": "web-2_2", "n": "16.2", "title": "Sell It: ₦20k–80k Monthly Email Retainers", "dur": "5 min",
"notes": "<span class='vault-tag'>🎙 Voice</span><h4>The Idea</h4><p>Target: anyone selling online with a customer list they ignore. Offer: 4 emails/month ₦20k, 8 + design ₦50k–80k. Emails print money for clients, so renewals are automatic.</p><div class='vault-action'><b>Action step:</b> Add email as a line item to your complete-brand package. Bundles close bigger.</div>" }
]},
{ "key": "web-m3", "title": "Skill 17 · Interactive 'Wow' Pages", "lessons": [
{ "key": "web-3_1", "n": "17.1", "title": "Learn & Build: Scroll Magic & Cursor Effects", "dur": "11 min",
"notes": "<span class='vault-tag'>🖥 Screen</span><h4>The Idea</h4><p>Image-reveal heroes, scroll-triggered video, mouse-scrub galleries — the effects that make a page feel expensive. You build them with AI from proven module specs; the Fuse Atelier sales page itself is your reference build.</p><div class='vault-action'><b>Action step:</b> Rebuild the image-reveal hero for your own portfolio page. Next: charging premium for premium.</div>" },
{ "key": "web-3_2", "n": "17.2", "title": "Sell It: The ₦150k+ Signature Site", "dur": "5 min",
"notes": "<span class='vault-tag'>🎙 Voice</span><h4>The Idea</h4><p>Interactive sites are for clients who sell status: premium brands, creators, event companies. Minimum ₦150k. Show, don't tell — your own wow-page portfolio does the selling.</p><div class='vault-action'><b>Action step:</b> Ship your own interactive portfolio page. It's simultaneously your proof, your pitch, and your product.</div>" }
]}
]},

{ "key": "money", "name": "THE MONEY ENGINE", "sub": "In every tier — the road from skill to salary", "tier": "starter", "modules": [
{ "key": "money-m1", "title": "Skill 18 · The First-Client System (7 Days)", "lessons": [
{ "key": "money-1_1", "n": "18.1", "title": "The 7-Day Plan, Day By Day", "dur": "8 min",
"notes": "<span class='vault-tag'>🎙 Voice</span><h4>The Idea</h4><p>Day 1 set up shop + pick skill · Day 2 build 3 proof pieces · Day 3 first 10 outreach messages · Days 4–5 follow up + keep sending · Day 6 close & deliver · Day 7 raise price + repeat. The WhatsApp coach walks you through each day and confirms every action.</p><div class='vault-action'><b>Action step:</b> Message the coach bot 'DAY 1' to activate your plan. From here, the system carries you.</div>" },
{ "key": "money-1_2", "n": "18.2", "title": "Your Proof Pieces & Simple Portfolio", "dur": "6 min",
"notes": "<span class='vault-tag'>🖥 Screen</span><h4>The Idea</h4><p>Nobody hires without proof — so manufacture it: 3 pieces in your skill for imaginary (or real local) businesses, arranged in a clean WhatsApp catalog + one Google Drive folder. That's a portfolio. Done beats perfect.</p><div class='vault-action'><b>Action step:</b> Assemble your 3 pieces into your catalog today. The coach will ask to see it.</div>" }
]},
{ "key": "money-m2", "title": "Skill 19 · Client Playbooks (Every Channel That Works)", "lessons": [
{ "key": "money-2_1", "n": "19.1", "title": "WhatsApp, Facebook & Walk-Ins (Fastest Naira)", "dur": "9 min",
"notes": "<span class='vault-tag'>🎙 Voice</span><h4>The Idea</h4><p>WhatsApp: status posts + business catalog + direct pitches to contacts who run businesses. Facebook: Nigerian business-owner groups (value first, pitch second). Walk-ins: redesign THEIR flyer/signage before you enter, show it on your phone, first job ₦2k–3k same-day. These three convert in 1–5 days.</p><div class='vault-action'><b>Action step:</b> Post your first before/after on status + join 2 business groups + pick one shop for a walk-in tomorrow.</div>" },
{ "key": "money-2_2", "n": "19.2", "title": "Instagram & TikTok (The Inbound Engine)", "dur": "8 min",
"notes": "<span class='vault-tag'>🎙 Voice</span><h4>The Idea</h4><p>IG: 10–15 personalized DMs daily WITH a pre-made sample for that exact business — the sample collapses the trust barrier. TikTok: one transformation post daily ('I made this ad with AI in 4 minutes') seeds inbound clients within weeks.</p><div class='vault-action'><b>Action step:</b> Send your first 10 sample-attached DMs using the vault scripts. Reply DONE to the coach when sent.</div>" },
{ "key": "money-2_3", "n": "19.3", "title": "Foreign & Diaspora Clients (The Dollar Playbook)", "dur": "9 min",
"notes": "<span class='vault-tag'>🎙 Voice</span><h4>The Idea</h4><p>Diaspora businesses (African restaurants, hair shops, event planners in the US/UK) pay in dollars and refer within tight networks. Find them on Google Maps + IG, make a free redesign of their flyer/menu/product photo, email or DM it attached with a 2-line pitch. Personalized samples lift replies 2–3x.</p><div class='vault-action'><b>Action step:</b> Find 5 diaspora businesses and make one free sample for the best one. Send it tonight.</div>" }
]},
{ "key": "money-m3", "title": "Skill 20 · Upwork, Taught From 12 Real Wins", "lessons": [
{ "key": "money-3_1", "n": "20.1", "title": "The Profile & Gigs That Landed 12 Jobs", "dur": "9 min",
"notes": "<span class='vault-tag'>🖥 Screen</span><h4>The Idea</h4><p>A teardown of the exact Upwork profile that earned $3,000+: the headline, the portfolio pieces, the niche positioning. Honest framing: Upwork is a weeks-2–4 channel, not a day-1 channel — build it while your local pipeline pays the bills.</p><div class='vault-action'><b>Action step:</b> Set up your profile copying the structure (not the words). Next: the proposals that won.</div>" },
{ "key": "gold-3_5", "n": "20.2", "title": "Pitch And Land Your First Client (Full Walkthrough)", "dur": "15 min",
"notes": "<span class='vault-tag'>🎙 Talking head — full recorded walkthrough</span><h4>The Idea</h4><p>The complete recorded walkthrough of pitching and landing a real client — the proposal structure, the free-sample hook, the close.</p><div class='vault-action'><b>Action step:</b> Send one real proposal using the approach shown, then post your experience in the community.</div>" },
{ "key": "money-3_3", "n": "20.3", "title": "Get Paid & Scale: Dollars, Pricing, Retainers", "dur": "8 min",
"notes": "<span class='vault-tag'>🎙 Voice</span><h4>The Idea</h4><p>Receiving dollars in Nigeria: Grey or Raenest for direct clients (free USD accounts, ~1% fees), Payoneer for marketplaces. Pricing ladders in ₦ and $. The retainer conversation that turns one job into monthly income. Nobody else teaches this part — it's why our students actually keep their money.</p><div class='vault-action'><b>Action step:</b> Open your Grey/Raenest account today (it's free) so a dollar client can never catch you unready.</div>" }
]}
]}

]};
